--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Debian 15.1-1.pgdg110+1)
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-09 16:25:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3338 (class 1262 OID 16388)
-- Name: Turkiye; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Turkiye" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "Turkiye" OWNER TO postgres;

\connect "Turkiye"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16390)
-- Name: Cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cities" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Cities" OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16389)
-- Name: Cities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16396)
-- Name: Districts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Districts" (
    "Id" integer NOT NULL,
    "CityId" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Districts" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16395)
-- Name: Districts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Districts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Districts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3330 (class 0 OID 16390)
-- Dependencies: 215
-- Data for Name: Cities; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Cities" VALUES (1, 'ADANA');
INSERT INTO public."Cities" VALUES (2, 'ADIYAMAN');
INSERT INTO public."Cities" VALUES (3, 'AFYONKARAHİSAR');
INSERT INTO public."Cities" VALUES (4, 'AĞRI');
INSERT INTO public."Cities" VALUES (5, 'AKSARAY');
INSERT INTO public."Cities" VALUES (6, 'AMASYA');
INSERT INTO public."Cities" VALUES (7, 'ANKARA');
INSERT INTO public."Cities" VALUES (8, 'ANTALYA');
INSERT INTO public."Cities" VALUES (9, 'ARDAHAN');
INSERT INTO public."Cities" VALUES (10, 'ARTVİN');
INSERT INTO public."Cities" VALUES (11, 'AYDIN');
INSERT INTO public."Cities" VALUES (12, 'BALIKESİR');
INSERT INTO public."Cities" VALUES (13, 'BARTIN');
INSERT INTO public."Cities" VALUES (14, 'BATMAN');
INSERT INTO public."Cities" VALUES (15, 'BAYBURT');
INSERT INTO public."Cities" VALUES (16, 'BİLECİK');
INSERT INTO public."Cities" VALUES (17, 'BİNGÖL');
INSERT INTO public."Cities" VALUES (18, 'BİTLİS');
INSERT INTO public."Cities" VALUES (19, 'BOLU');
INSERT INTO public."Cities" VALUES (20, 'BURDUR');
INSERT INTO public."Cities" VALUES (21, 'BURSA');
INSERT INTO public."Cities" VALUES (22, 'ÇANAKKALE');
INSERT INTO public."Cities" VALUES (23, 'ÇANKIRI');
INSERT INTO public."Cities" VALUES (24, 'ÇORUM');
INSERT INTO public."Cities" VALUES (25, 'DENİZLİ');
INSERT INTO public."Cities" VALUES (26, 'DİYARBAKIR');
INSERT INTO public."Cities" VALUES (27, 'DÜZCE');
INSERT INTO public."Cities" VALUES (28, 'EDİRNE');
INSERT INTO public."Cities" VALUES (29, 'ELAZIĞ');
INSERT INTO public."Cities" VALUES (30, 'ERZİNCAN');
INSERT INTO public."Cities" VALUES (31, 'ERZURUM');
INSERT INTO public."Cities" VALUES (32, 'ESKİŞEHİR');
INSERT INTO public."Cities" VALUES (33, 'GAZİANTEP');
INSERT INTO public."Cities" VALUES (34, 'GİRESUN');
INSERT INTO public."Cities" VALUES (35, 'GÜMÜŞHANE');
INSERT INTO public."Cities" VALUES (36, 'HAKKARİ');
INSERT INTO public."Cities" VALUES (37, 'HATAY');
INSERT INTO public."Cities" VALUES (38, 'IĞDIR');
INSERT INTO public."Cities" VALUES (39, 'ISPARTA');
INSERT INTO public."Cities" VALUES (40, 'İSTANBUL');
INSERT INTO public."Cities" VALUES (41, 'İZMİR');
INSERT INTO public."Cities" VALUES (42, 'KAHRAMANMARAŞ');
INSERT INTO public."Cities" VALUES (43, 'KARABÜK');
INSERT INTO public."Cities" VALUES (44, 'KARAMAN');
INSERT INTO public."Cities" VALUES (45, 'KARS');
INSERT INTO public."Cities" VALUES (46, 'KASTAMONU');
INSERT INTO public."Cities" VALUES (47, 'KAYSERİ');
INSERT INTO public."Cities" VALUES (48, 'KİLİS');
INSERT INTO public."Cities" VALUES (49, 'KIRIKKALE');
INSERT INTO public."Cities" VALUES (50, 'KIRKLARELİ');
INSERT INTO public."Cities" VALUES (51, 'KIRŞEHİR');
INSERT INTO public."Cities" VALUES (52, 'KOCAELİ');
INSERT INTO public."Cities" VALUES (53, 'KONYA');
INSERT INTO public."Cities" VALUES (54, 'KÜTAHYA');
INSERT INTO public."Cities" VALUES (55, 'MALATYA');
INSERT INTO public."Cities" VALUES (56, 'MANİSA');
INSERT INTO public."Cities" VALUES (57, 'MARDİN');
INSERT INTO public."Cities" VALUES (58, 'MERSİN');
INSERT INTO public."Cities" VALUES (59, 'MUĞLA');
INSERT INTO public."Cities" VALUES (60, 'MUŞ');
INSERT INTO public."Cities" VALUES (61, 'NEVŞEHİR');
INSERT INTO public."Cities" VALUES (62, 'NİĞDE');
INSERT INTO public."Cities" VALUES (63, 'ORDU');
INSERT INTO public."Cities" VALUES (64, 'OSMANİYE');
INSERT INTO public."Cities" VALUES (65, 'RİZE');
INSERT INTO public."Cities" VALUES (66, 'SAKARYA');
INSERT INTO public."Cities" VALUES (67, 'SAMSUN');
INSERT INTO public."Cities" VALUES (68, 'ŞANLIURFA');
INSERT INTO public."Cities" VALUES (69, 'SİİRT');
INSERT INTO public."Cities" VALUES (70, 'SİNOP');
INSERT INTO public."Cities" VALUES (71, 'ŞIRNAK');
INSERT INTO public."Cities" VALUES (72, 'SİVAS');
INSERT INTO public."Cities" VALUES (73, 'TEKİRDAĞ');
INSERT INTO public."Cities" VALUES (74, 'TOKAT');
INSERT INTO public."Cities" VALUES (75, 'TRABZON');
INSERT INTO public."Cities" VALUES (76, 'TUNCELİ');
INSERT INTO public."Cities" VALUES (77, 'UŞAK');
INSERT INTO public."Cities" VALUES (78, 'VAN');
INSERT INTO public."Cities" VALUES (79, 'YALOVA');
INSERT INTO public."Cities" VALUES (80, 'YOZGAT');
INSERT INTO public."Cities" VALUES (81, 'ZONGULDAK');


--
-- TOC entry 3332 (class 0 OID 16396)
-- Dependencies: 217
-- Data for Name: Districts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Districts" VALUES (1, 1, 'ALADAĞ');
INSERT INTO public."Districts" VALUES (2, 1, 'CEYHAN');
INSERT INTO public."Districts" VALUES (3, 1, 'ÇUKUROVA');
INSERT INTO public."Districts" VALUES (4, 1, 'FEKE');
INSERT INTO public."Districts" VALUES (5, 1, 'İMAMOĞLU');
INSERT INTO public."Districts" VALUES (6, 1, 'KARAİSALI');
INSERT INTO public."Districts" VALUES (7, 1, 'KARATAŞ');
INSERT INTO public."Districts" VALUES (8, 1, 'KOZAN');
INSERT INTO public."Districts" VALUES (9, 1, 'POZANTI');
INSERT INTO public."Districts" VALUES (10, 1, 'SAİMBEYLİ');
INSERT INTO public."Districts" VALUES (11, 1, 'SARIÇAM');
INSERT INTO public."Districts" VALUES (12, 1, 'SEYHAN');
INSERT INTO public."Districts" VALUES (13, 1, 'TUFANBEYLİ');
INSERT INTO public."Districts" VALUES (14, 1, 'YUMURTALIK');
INSERT INTO public."Districts" VALUES (15, 1, 'YÜREĞİR');
INSERT INTO public."Districts" VALUES (16, 2, 'BESNİ');
INSERT INTO public."Districts" VALUES (17, 2, 'ÇELİKHAN');
INSERT INTO public."Districts" VALUES (18, 2, 'GERGER');
INSERT INTO public."Districts" VALUES (19, 2, 'GÖLBAŞI');
INSERT INTO public."Districts" VALUES (20, 2, 'KAHTA');
INSERT INTO public."Districts" VALUES (21, 2, 'SAMSAT');
INSERT INTO public."Districts" VALUES (22, 2, 'SİNCİK');
INSERT INTO public."Districts" VALUES (23, 2, 'TUT');
INSERT INTO public."Districts" VALUES (24, 3, 'BAŞMAKÇI');
INSERT INTO public."Districts" VALUES (25, 3, 'BAYAT');
INSERT INTO public."Districts" VALUES (26, 3, 'BOLVADİN');
INSERT INTO public."Districts" VALUES (27, 3, 'ÇAY');
INSERT INTO public."Districts" VALUES (28, 3, 'ÇOBANLAR');
INSERT INTO public."Districts" VALUES (29, 3, 'DAZKIRI');
INSERT INTO public."Districts" VALUES (30, 3, 'DİNAR');
INSERT INTO public."Districts" VALUES (31, 3, 'EMİRDAĞ');
INSERT INTO public."Districts" VALUES (32, 3, 'EVCİLER');
INSERT INTO public."Districts" VALUES (33, 3, 'HOCALAR');
INSERT INTO public."Districts" VALUES (34, 3, 'İHSANİYE');
INSERT INTO public."Districts" VALUES (35, 3, 'İSCEHİSAR');
INSERT INTO public."Districts" VALUES (36, 3, 'KIZILÖREN');
INSERT INTO public."Districts" VALUES (37, 3, 'SANDIKLI');
INSERT INTO public."Districts" VALUES (38, 3, 'SİNANPAŞA');
INSERT INTO public."Districts" VALUES (39, 3, 'ŞUHUT');
INSERT INTO public."Districts" VALUES (40, 3, 'SULTANDAĞI');
INSERT INTO public."Districts" VALUES (41, 4, 'DİYADİN');
INSERT INTO public."Districts" VALUES (42, 4, 'DOĞUBAYAZIT');
INSERT INTO public."Districts" VALUES (43, 4, 'ELEŞKİRT');
INSERT INTO public."Districts" VALUES (44, 4, 'HAMUR');
INSERT INTO public."Districts" VALUES (45, 4, 'PATNOS');
INSERT INTO public."Districts" VALUES (46, 4, 'TAŞLIÇAY');
INSERT INTO public."Districts" VALUES (47, 4, 'TUTAK');
INSERT INTO public."Districts" VALUES (48, 5, 'AĞAÇÖREN');
INSERT INTO public."Districts" VALUES (49, 5, 'ESKİL');
INSERT INTO public."Districts" VALUES (50, 5, 'GÜLAĞAÇ');
INSERT INTO public."Districts" VALUES (51, 5, 'GÜZELYURT');
INSERT INTO public."Districts" VALUES (52, 5, 'ORTAKÖY');
INSERT INTO public."Districts" VALUES (53, 5, 'SARIYAHŞİ');
INSERT INTO public."Districts" VALUES (54, 5, 'SULTANHANI');
INSERT INTO public."Districts" VALUES (55, 6, 'GÖYNÜCEK');
INSERT INTO public."Districts" VALUES (56, 6, 'GÜMÜŞHACIKÖY');
INSERT INTO public."Districts" VALUES (57, 6, 'HAMAMÖZÜ');
INSERT INTO public."Districts" VALUES (58, 6, 'MERZİFON');
INSERT INTO public."Districts" VALUES (59, 6, 'SULUOVA');
INSERT INTO public."Districts" VALUES (60, 6, 'TAŞOVA');
INSERT INTO public."Districts" VALUES (61, 7, 'AKYURT');
INSERT INTO public."Districts" VALUES (62, 7, 'ALTINDAĞ');
INSERT INTO public."Districts" VALUES (63, 7, 'AYAŞ');
INSERT INTO public."Districts" VALUES (64, 7, 'BALA');
INSERT INTO public."Districts" VALUES (65, 7, 'BEYPAZARI');
INSERT INTO public."Districts" VALUES (66, 7, 'ÇAMLIDERE');
INSERT INTO public."Districts" VALUES (67, 7, 'ÇANKAYA');
INSERT INTO public."Districts" VALUES (68, 7, 'ÇUBUK');
INSERT INTO public."Districts" VALUES (69, 7, 'ELMADAĞ');
INSERT INTO public."Districts" VALUES (70, 7, 'ETİMESGUT');
INSERT INTO public."Districts" VALUES (71, 7, 'EVREN');
INSERT INTO public."Districts" VALUES (72, 7, 'GÖLBAŞI');
INSERT INTO public."Districts" VALUES (73, 7, 'GÜDÜL');
INSERT INTO public."Districts" VALUES (74, 7, 'HAYMANA');
INSERT INTO public."Districts" VALUES (75, 7, 'KAHRAMANKAZAN');
INSERT INTO public."Districts" VALUES (76, 7, 'KALECİK');
INSERT INTO public."Districts" VALUES (77, 7, 'KEÇİÖREN');
INSERT INTO public."Districts" VALUES (78, 7, 'KIZILCAHAMAM');
INSERT INTO public."Districts" VALUES (79, 7, 'MAMAK');
INSERT INTO public."Districts" VALUES (80, 7, 'NALLIHAN');
INSERT INTO public."Districts" VALUES (81, 7, 'POLATLI');
INSERT INTO public."Districts" VALUES (82, 7, 'PURSAKLAR');
INSERT INTO public."Districts" VALUES (83, 7, 'ŞEREFLİKOÇHİSAR');
INSERT INTO public."Districts" VALUES (84, 7, 'SİNCAN');
INSERT INTO public."Districts" VALUES (85, 7, 'YENİMAHALLE');
INSERT INTO public."Districts" VALUES (86, 8, 'AKSEKİ');
INSERT INTO public."Districts" VALUES (87, 8, 'AKSU');
INSERT INTO public."Districts" VALUES (88, 8, 'ALANYA');
INSERT INTO public."Districts" VALUES (89, 8, 'DEMRE');
INSERT INTO public."Districts" VALUES (90, 8, 'DÖŞEMEALTI');
INSERT INTO public."Districts" VALUES (91, 8, 'ELMALI');
INSERT INTO public."Districts" VALUES (92, 8, 'FİNİKE');
INSERT INTO public."Districts" VALUES (93, 8, 'GAZİPAŞA');
INSERT INTO public."Districts" VALUES (94, 8, 'GÜNDOĞMUŞ');
INSERT INTO public."Districts" VALUES (95, 8, 'İBRADI');
INSERT INTO public."Districts" VALUES (96, 8, 'KAŞ');
INSERT INTO public."Districts" VALUES (97, 8, 'KEMER');
INSERT INTO public."Districts" VALUES (98, 8, 'KEPEZ');
INSERT INTO public."Districts" VALUES (99, 8, 'KONYAALTI');
INSERT INTO public."Districts" VALUES (100, 8, 'KORKUTELİ');
INSERT INTO public."Districts" VALUES (101, 8, 'KUMLUCA');
INSERT INTO public."Districts" VALUES (102, 8, 'MANAVGAT');
INSERT INTO public."Districts" VALUES (103, 8, 'MURATPAŞA');
INSERT INTO public."Districts" VALUES (104, 8, 'SERİK');
INSERT INTO public."Districts" VALUES (105, 9, 'ÇILDIR');
INSERT INTO public."Districts" VALUES (106, 9, 'DAMAL');
INSERT INTO public."Districts" VALUES (107, 9, 'GÖLE');
INSERT INTO public."Districts" VALUES (108, 9, 'HANAK');
INSERT INTO public."Districts" VALUES (109, 9, 'POSOF');
INSERT INTO public."Districts" VALUES (110, 10, 'ARDANUÇ');
INSERT INTO public."Districts" VALUES (111, 10, 'ARHAVİ');
INSERT INTO public."Districts" VALUES (112, 10, 'BORÇKA');
INSERT INTO public."Districts" VALUES (113, 10, 'HOPA');
INSERT INTO public."Districts" VALUES (114, 10, 'KEMALPAŞA');
INSERT INTO public."Districts" VALUES (115, 10, 'MURGUL');
INSERT INTO public."Districts" VALUES (116, 10, 'ŞAVŞAT');
INSERT INTO public."Districts" VALUES (117, 10, 'YUSUFELİ');
INSERT INTO public."Districts" VALUES (118, 11, 'BOZDOĞAN');
INSERT INTO public."Districts" VALUES (119, 11, 'BUHARKENT');
INSERT INTO public."Districts" VALUES (120, 11, 'ÇİNE');
INSERT INTO public."Districts" VALUES (121, 11, 'DİDİM');
INSERT INTO public."Districts" VALUES (122, 11, 'EFELER');
INSERT INTO public."Districts" VALUES (123, 11, 'GERMENCİK');
INSERT INTO public."Districts" VALUES (124, 11, 'İNCİRLİOVA');
INSERT INTO public."Districts" VALUES (125, 11, 'KARACASU');
INSERT INTO public."Districts" VALUES (126, 11, 'KARPUZLU');
INSERT INTO public."Districts" VALUES (127, 11, 'KOÇARLI');
INSERT INTO public."Districts" VALUES (128, 11, 'KÖŞK');
INSERT INTO public."Districts" VALUES (129, 11, 'KUŞADASI');
INSERT INTO public."Districts" VALUES (130, 11, 'KUYUCAK');
INSERT INTO public."Districts" VALUES (131, 11, 'NAZİLLİ');
INSERT INTO public."Districts" VALUES (132, 11, 'SÖKE');
INSERT INTO public."Districts" VALUES (133, 11, 'SULTANHİSAR');
INSERT INTO public."Districts" VALUES (134, 11, 'YENİPAZAR');
INSERT INTO public."Districts" VALUES (135, 12, 'ALTIEYLÜL');
INSERT INTO public."Districts" VALUES (136, 12, 'AYVALIK');
INSERT INTO public."Districts" VALUES (137, 12, 'BALYA');
INSERT INTO public."Districts" VALUES (138, 12, 'BANDIRMA');
INSERT INTO public."Districts" VALUES (139, 12, 'BİGADİÇ');
INSERT INTO public."Districts" VALUES (140, 12, 'BURHANİYE');
INSERT INTO public."Districts" VALUES (141, 12, 'DURSUNBEY');
INSERT INTO public."Districts" VALUES (142, 12, 'EDREMİT');
INSERT INTO public."Districts" VALUES (143, 12, 'ERDEK');
INSERT INTO public."Districts" VALUES (144, 12, 'GÖMEÇ');
INSERT INTO public."Districts" VALUES (145, 12, 'GÖNEN');
INSERT INTO public."Districts" VALUES (146, 12, 'HAVRAN');
INSERT INTO public."Districts" VALUES (147, 12, 'İVRİNDİ');
INSERT INTO public."Districts" VALUES (148, 12, 'KARESİ');
INSERT INTO public."Districts" VALUES (149, 12, 'KEPSUT');
INSERT INTO public."Districts" VALUES (150, 12, 'MANYAS');
INSERT INTO public."Districts" VALUES (151, 12, 'MARMARA');
INSERT INTO public."Districts" VALUES (152, 12, 'SAVAŞTEPE');
INSERT INTO public."Districts" VALUES (153, 12, 'SINDIRGI');
INSERT INTO public."Districts" VALUES (154, 12, 'SUSURLUK');
INSERT INTO public."Districts" VALUES (155, 13, 'AMASRA');
INSERT INTO public."Districts" VALUES (156, 13, 'KURUCAŞİLE');
INSERT INTO public."Districts" VALUES (157, 13, 'ULUS');
INSERT INTO public."Districts" VALUES (158, 14, 'BEŞİRİ');
INSERT INTO public."Districts" VALUES (159, 14, 'GERCÜŞ');
INSERT INTO public."Districts" VALUES (160, 14, 'HASANKEYF');
INSERT INTO public."Districts" VALUES (161, 14, 'KOZLUK');
INSERT INTO public."Districts" VALUES (162, 14, 'SASON');
INSERT INTO public."Districts" VALUES (163, 15, 'AYDINTEPE');
INSERT INTO public."Districts" VALUES (164, 15, 'DEMİRÖZÜ');
INSERT INTO public."Districts" VALUES (165, 16, 'BOZÜYÜK');
INSERT INTO public."Districts" VALUES (166, 16, 'GÖLPAZARI');
INSERT INTO public."Districts" VALUES (167, 16, 'İNHİSAR');
INSERT INTO public."Districts" VALUES (168, 16, 'OSMANELİ');
INSERT INTO public."Districts" VALUES (169, 16, 'PAZARYERİ');
INSERT INTO public."Districts" VALUES (170, 16, 'SÖĞÜT');
INSERT INTO public."Districts" VALUES (171, 16, 'YENİPAZAR');
INSERT INTO public."Districts" VALUES (172, 17, 'ADAKLI');
INSERT INTO public."Districts" VALUES (173, 17, 'GENÇ');
INSERT INTO public."Districts" VALUES (174, 17, 'KARLIOVA');
INSERT INTO public."Districts" VALUES (175, 17, 'KİĞI');
INSERT INTO public."Districts" VALUES (176, 17, 'SOLHAN');
INSERT INTO public."Districts" VALUES (177, 17, 'YAYLADERE');
INSERT INTO public."Districts" VALUES (178, 17, 'YEDİSU');
INSERT INTO public."Districts" VALUES (179, 18, 'ADİLCEVAZ');
INSERT INTO public."Districts" VALUES (180, 18, 'AHLAT');
INSERT INTO public."Districts" VALUES (181, 18, 'GÜROYMAK');
INSERT INTO public."Districts" VALUES (182, 18, 'HİZAN');
INSERT INTO public."Districts" VALUES (183, 18, 'MUTKİ');
INSERT INTO public."Districts" VALUES (184, 18, 'TATVAN');
INSERT INTO public."Districts" VALUES (185, 19, 'DÖRTDİVAN');
INSERT INTO public."Districts" VALUES (186, 19, 'GEREDE');
INSERT INTO public."Districts" VALUES (187, 19, 'GÖYNÜK');
INSERT INTO public."Districts" VALUES (188, 19, 'KIBRISCIK');
INSERT INTO public."Districts" VALUES (189, 19, 'MENGEN');
INSERT INTO public."Districts" VALUES (190, 19, 'MUDURNU');
INSERT INTO public."Districts" VALUES (191, 19, 'SEBEN');
INSERT INTO public."Districts" VALUES (192, 19, 'YENİÇAĞA');
INSERT INTO public."Districts" VALUES (193, 20, 'AĞLASUN');
INSERT INTO public."Districts" VALUES (194, 20, 'ALTINYAYLA');
INSERT INTO public."Districts" VALUES (195, 20, 'BUCAK');
INSERT INTO public."Districts" VALUES (196, 20, 'ÇAVDIR');
INSERT INTO public."Districts" VALUES (197, 20, 'ÇELTİKÇİ');
INSERT INTO public."Districts" VALUES (198, 20, 'GÖLHİSAR');
INSERT INTO public."Districts" VALUES (199, 20, 'KARAMANLI');
INSERT INTO public."Districts" VALUES (200, 20, 'KEMER');
INSERT INTO public."Districts" VALUES (201, 20, 'TEFENNİ');
INSERT INTO public."Districts" VALUES (202, 20, 'YEŞİLOVA');
INSERT INTO public."Districts" VALUES (203, 21, 'BÜYÜKORHAN');
INSERT INTO public."Districts" VALUES (204, 21, 'GEMLİK');
INSERT INTO public."Districts" VALUES (205, 21, 'GÜRSU');
INSERT INTO public."Districts" VALUES (206, 21, 'HARMANCIK');
INSERT INTO public."Districts" VALUES (207, 21, 'İNEGÖL');
INSERT INTO public."Districts" VALUES (208, 21, 'İZNİK');
INSERT INTO public."Districts" VALUES (209, 21, 'KARACABEY');
INSERT INTO public."Districts" VALUES (210, 21, 'KELES');
INSERT INTO public."Districts" VALUES (211, 21, 'KESTEL');
INSERT INTO public."Districts" VALUES (212, 21, 'MUDANYA');
INSERT INTO public."Districts" VALUES (213, 21, 'MUSTAFAKEMALPAŞA');
INSERT INTO public."Districts" VALUES (214, 21, 'NİLÜFER');
INSERT INTO public."Districts" VALUES (215, 21, 'ORHANELİ');
INSERT INTO public."Districts" VALUES (216, 21, 'ORHANGAZİ');
INSERT INTO public."Districts" VALUES (217, 21, 'OSMANGAZİ');
INSERT INTO public."Districts" VALUES (218, 21, 'YENİŞEHİR');
INSERT INTO public."Districts" VALUES (219, 21, 'YILDIRIM');
INSERT INTO public."Districts" VALUES (220, 22, 'AYVACIK');
INSERT INTO public."Districts" VALUES (221, 22, 'BAYRAMİÇ');
INSERT INTO public."Districts" VALUES (222, 22, 'BİGA');
INSERT INTO public."Districts" VALUES (223, 22, 'BOZCAADA');
INSERT INTO public."Districts" VALUES (224, 22, 'ÇAN');
INSERT INTO public."Districts" VALUES (225, 22, 'ECEABAT');
INSERT INTO public."Districts" VALUES (226, 22, 'EZİNE');
INSERT INTO public."Districts" VALUES (227, 22, 'GELİBOLU');
INSERT INTO public."Districts" VALUES (228, 22, 'GÖKÇEADA');
INSERT INTO public."Districts" VALUES (229, 22, 'LAPSEKİ');
INSERT INTO public."Districts" VALUES (230, 22, 'YENİCE');
INSERT INTO public."Districts" VALUES (231, 23, 'ATKARACALAR');
INSERT INTO public."Districts" VALUES (232, 23, 'BAYRAMÖREN');
INSERT INTO public."Districts" VALUES (233, 23, 'ÇERKEŞ');
INSERT INTO public."Districts" VALUES (234, 23, 'ELDİVAN');
INSERT INTO public."Districts" VALUES (235, 23, 'ILGAZ');
INSERT INTO public."Districts" VALUES (236, 23, 'KIZILIRMAK');
INSERT INTO public."Districts" VALUES (237, 23, 'KORGUN');
INSERT INTO public."Districts" VALUES (238, 23, 'KURŞUNLU');
INSERT INTO public."Districts" VALUES (239, 23, 'ORTA');
INSERT INTO public."Districts" VALUES (240, 23, 'ŞABANÖZÜ');
INSERT INTO public."Districts" VALUES (241, 23, 'YAPRAKLI');
INSERT INTO public."Districts" VALUES (242, 24, 'ALACA');
INSERT INTO public."Districts" VALUES (243, 24, 'BAYAT');
INSERT INTO public."Districts" VALUES (244, 24, 'BOĞAZKALE');
INSERT INTO public."Districts" VALUES (245, 24, 'DODURGA');
INSERT INTO public."Districts" VALUES (246, 24, 'İSKİLİP');
INSERT INTO public."Districts" VALUES (247, 24, 'KARGI');
INSERT INTO public."Districts" VALUES (248, 24, 'LAÇİN');
INSERT INTO public."Districts" VALUES (249, 24, 'MECİTÖZÜ');
INSERT INTO public."Districts" VALUES (250, 24, 'OĞUZLAR');
INSERT INTO public."Districts" VALUES (251, 24, 'ORTAKÖY');
INSERT INTO public."Districts" VALUES (252, 24, 'OSMANCIK');
INSERT INTO public."Districts" VALUES (253, 24, 'SUNGURLU');
INSERT INTO public."Districts" VALUES (254, 24, 'UĞURLUDAĞ');
INSERT INTO public."Districts" VALUES (255, 25, 'ACIPAYAM');
INSERT INTO public."Districts" VALUES (256, 25, 'BABADAĞ');
INSERT INTO public."Districts" VALUES (257, 25, 'BAKLAN');
INSERT INTO public."Districts" VALUES (258, 25, 'BEKİLLİ');
INSERT INTO public."Districts" VALUES (259, 25, 'BEYAĞAÇ');
INSERT INTO public."Districts" VALUES (260, 25, 'BOZKURT');
INSERT INTO public."Districts" VALUES (261, 25, 'BULDAN');
INSERT INTO public."Districts" VALUES (262, 25, 'ÇAL');
INSERT INTO public."Districts" VALUES (263, 25, 'ÇAMELİ');
INSERT INTO public."Districts" VALUES (264, 25, 'ÇARDAK');
INSERT INTO public."Districts" VALUES (265, 25, 'ÇİVRİL');
INSERT INTO public."Districts" VALUES (266, 25, 'GÜNEY');
INSERT INTO public."Districts" VALUES (267, 25, 'HONAZ');
INSERT INTO public."Districts" VALUES (268, 25, 'KALE');
INSERT INTO public."Districts" VALUES (269, 25, 'MERKEZEFENDİ');
INSERT INTO public."Districts" VALUES (270, 25, 'PAMUKKALE');
INSERT INTO public."Districts" VALUES (271, 25, 'SARAYKÖY');
INSERT INTO public."Districts" VALUES (272, 25, 'SERİNHİSAR');
INSERT INTO public."Districts" VALUES (273, 25, 'TAVAS');
INSERT INTO public."Districts" VALUES (274, 26, 'BAĞLAR');
INSERT INTO public."Districts" VALUES (275, 26, 'BİSMİL');
INSERT INTO public."Districts" VALUES (276, 26, 'ÇERMİK');
INSERT INTO public."Districts" VALUES (277, 26, 'ÇINAR');
INSERT INTO public."Districts" VALUES (278, 26, 'ÇÜNGÜŞ');
INSERT INTO public."Districts" VALUES (279, 26, 'DİCLE');
INSERT INTO public."Districts" VALUES (280, 26, 'EĞİL');
INSERT INTO public."Districts" VALUES (281, 26, 'ERGANİ');
INSERT INTO public."Districts" VALUES (282, 26, 'HANİ');
INSERT INTO public."Districts" VALUES (283, 26, 'HAZRO');
INSERT INTO public."Districts" VALUES (284, 26, 'KAYAPINAR');
INSERT INTO public."Districts" VALUES (285, 26, 'KOCAKÖY');
INSERT INTO public."Districts" VALUES (286, 26, 'KULP');
INSERT INTO public."Districts" VALUES (287, 26, 'LİCE');
INSERT INTO public."Districts" VALUES (288, 26, 'SİLVAN');
INSERT INTO public."Districts" VALUES (289, 26, 'SUR');
INSERT INTO public."Districts" VALUES (290, 26, 'YENİŞEHİR');
INSERT INTO public."Districts" VALUES (291, 27, 'AKÇAKOCA');
INSERT INTO public."Districts" VALUES (292, 27, 'ÇİLİMLİ');
INSERT INTO public."Districts" VALUES (293, 27, 'CUMAYERİ');
INSERT INTO public."Districts" VALUES (294, 27, 'GÖLYAKA');
INSERT INTO public."Districts" VALUES (295, 27, 'GÜMÜŞOVA');
INSERT INTO public."Districts" VALUES (296, 27, 'KAYNAŞLI');
INSERT INTO public."Districts" VALUES (297, 27, 'YIĞILCA');
INSERT INTO public."Districts" VALUES (298, 28, 'ENEZ');
INSERT INTO public."Districts" VALUES (299, 28, 'HAVSA');
INSERT INTO public."Districts" VALUES (300, 28, 'İPSALA');
INSERT INTO public."Districts" VALUES (301, 28, 'KEŞAN');
INSERT INTO public."Districts" VALUES (302, 28, 'LALAPAŞA');
INSERT INTO public."Districts" VALUES (303, 28, 'MERİÇ');
INSERT INTO public."Districts" VALUES (304, 28, 'SÜLOĞLU');
INSERT INTO public."Districts" VALUES (305, 28, 'UZUNKÖPRÜ');
INSERT INTO public."Districts" VALUES (306, 29, 'AĞIN');
INSERT INTO public."Districts" VALUES (307, 29, 'ALACAKAYA');
INSERT INTO public."Districts" VALUES (308, 29, 'ARICAK');
INSERT INTO public."Districts" VALUES (309, 29, 'BASKİL');
INSERT INTO public."Districts" VALUES (310, 29, 'KARAKOÇAN');
INSERT INTO public."Districts" VALUES (311, 29, 'KEBAN');
INSERT INTO public."Districts" VALUES (312, 29, 'KOVANCILAR');
INSERT INTO public."Districts" VALUES (313, 29, 'MADEN');
INSERT INTO public."Districts" VALUES (314, 29, 'PALU');
INSERT INTO public."Districts" VALUES (315, 29, 'SİVRİCE');
INSERT INTO public."Districts" VALUES (316, 30, 'ÇAYIRLI');
INSERT INTO public."Districts" VALUES (317, 30, 'İLİÇ');
INSERT INTO public."Districts" VALUES (318, 30, 'KEMAH');
INSERT INTO public."Districts" VALUES (319, 30, 'KEMALİYE');
INSERT INTO public."Districts" VALUES (320, 30, 'OTLUKBELİ');
INSERT INTO public."Districts" VALUES (321, 30, 'REFAHİYE');
INSERT INTO public."Districts" VALUES (322, 30, 'TERCAN');
INSERT INTO public."Districts" VALUES (323, 30, 'ÜZÜMLÜ');
INSERT INTO public."Districts" VALUES (324, 31, 'AŞKALE');
INSERT INTO public."Districts" VALUES (325, 31, 'AZİZİYE');
INSERT INTO public."Districts" VALUES (326, 31, 'ÇAT');
INSERT INTO public."Districts" VALUES (327, 31, 'HINIS');
INSERT INTO public."Districts" VALUES (328, 31, 'HORASAN');
INSERT INTO public."Districts" VALUES (329, 31, 'İSPİR');
INSERT INTO public."Districts" VALUES (330, 31, 'KARAÇOBAN');
INSERT INTO public."Districts" VALUES (331, 31, 'KARAYAZI');
INSERT INTO public."Districts" VALUES (332, 31, 'KÖPRÜKÖY');
INSERT INTO public."Districts" VALUES (333, 31, 'NARMAN');
INSERT INTO public."Districts" VALUES (334, 31, 'OLTU');
INSERT INTO public."Districts" VALUES (335, 31, 'OLUR');
INSERT INTO public."Districts" VALUES (336, 31, 'PALANDÖKEN');
INSERT INTO public."Districts" VALUES (337, 31, 'PASİNLER');
INSERT INTO public."Districts" VALUES (338, 31, 'PAZARYOLU');
INSERT INTO public."Districts" VALUES (339, 31, 'ŞENKAYA');
INSERT INTO public."Districts" VALUES (340, 31, 'TEKMAN');
INSERT INTO public."Districts" VALUES (341, 31, 'TORTUM');
INSERT INTO public."Districts" VALUES (342, 31, 'UZUNDERE');
INSERT INTO public."Districts" VALUES (343, 31, 'YAKUTİYE');
INSERT INTO public."Districts" VALUES (344, 32, 'ALPU');
INSERT INTO public."Districts" VALUES (345, 32, 'BEYLİKOVA');
INSERT INTO public."Districts" VALUES (346, 32, 'ÇİFTELER');
INSERT INTO public."Districts" VALUES (347, 32, 'GÜNYÜZÜ');
INSERT INTO public."Districts" VALUES (348, 32, 'HAN');
INSERT INTO public."Districts" VALUES (349, 32, 'İNÖNÜ');
INSERT INTO public."Districts" VALUES (350, 32, 'MAHMUDİYE');
INSERT INTO public."Districts" VALUES (351, 32, 'MİHALGAZİ');
INSERT INTO public."Districts" VALUES (352, 32, 'MİHALIÇÇIK');
INSERT INTO public."Districts" VALUES (353, 32, 'ODUNPAZARI');
INSERT INTO public."Districts" VALUES (354, 32, 'SARICAKAYA');
INSERT INTO public."Districts" VALUES (355, 32, 'SEYİTGAZİ');
INSERT INTO public."Districts" VALUES (356, 32, 'SİVRİHİSAR');
INSERT INTO public."Districts" VALUES (357, 32, 'TEPEBAŞI');
INSERT INTO public."Districts" VALUES (358, 33, 'ARABAN');
INSERT INTO public."Districts" VALUES (359, 33, 'İSLAHİYE');
INSERT INTO public."Districts" VALUES (360, 33, 'KARKAMIŞ');
INSERT INTO public."Districts" VALUES (361, 33, 'NİZİP');
INSERT INTO public."Districts" VALUES (362, 33, 'NURDAĞI');
INSERT INTO public."Districts" VALUES (363, 33, 'OĞUZELİ');
INSERT INTO public."Districts" VALUES (364, 33, 'ŞAHİNBEY');
INSERT INTO public."Districts" VALUES (365, 33, 'ŞEHİTKAMİL');
INSERT INTO public."Districts" VALUES (366, 33, 'YAVUZELİ');
INSERT INTO public."Districts" VALUES (367, 34, 'ALUCRA');
INSERT INTO public."Districts" VALUES (368, 34, 'BULANCAK');
INSERT INTO public."Districts" VALUES (369, 34, 'ÇAMOLUK');
INSERT INTO public."Districts" VALUES (370, 34, 'ÇANAKÇI');
INSERT INTO public."Districts" VALUES (371, 34, 'DERELİ');
INSERT INTO public."Districts" VALUES (372, 34, 'DOĞANKENT');
INSERT INTO public."Districts" VALUES (373, 34, 'ESPİYE');
INSERT INTO public."Districts" VALUES (374, 34, 'EYNESİL');
INSERT INTO public."Districts" VALUES (375, 34, 'GÖRELE');
INSERT INTO public."Districts" VALUES (376, 34, 'GÜCE');
INSERT INTO public."Districts" VALUES (377, 34, 'KEŞAP');
INSERT INTO public."Districts" VALUES (378, 34, 'PİRAZİZ');
INSERT INTO public."Districts" VALUES (379, 34, 'ŞEBİNKARAHİSAR');
INSERT INTO public."Districts" VALUES (380, 34, 'TİREBOLU');
INSERT INTO public."Districts" VALUES (381, 34, 'YAĞLIDERE');
INSERT INTO public."Districts" VALUES (382, 35, 'KELKİT');
INSERT INTO public."Districts" VALUES (383, 35, 'KÖSE');
INSERT INTO public."Districts" VALUES (384, 35, 'KÜRTÜN');
INSERT INTO public."Districts" VALUES (385, 35, 'ŞİRAN');
INSERT INTO public."Districts" VALUES (386, 35, 'TORUL');
INSERT INTO public."Districts" VALUES (387, 36, 'ÇUKURCA');
INSERT INTO public."Districts" VALUES (388, 36, 'DERECİK');
INSERT INTO public."Districts" VALUES (389, 36, 'ŞEMDİNLİ');
INSERT INTO public."Districts" VALUES (390, 36, 'YÜKSEKOVA');
INSERT INTO public."Districts" VALUES (391, 37, 'ALTINÖZÜ');
INSERT INTO public."Districts" VALUES (392, 37, 'ANTAKYA');
INSERT INTO public."Districts" VALUES (393, 37, 'ARSUZ');
INSERT INTO public."Districts" VALUES (394, 37, 'BELEN');
INSERT INTO public."Districts" VALUES (395, 37, 'DEFNE');
INSERT INTO public."Districts" VALUES (396, 37, 'DÖRTYOL');
INSERT INTO public."Districts" VALUES (397, 37, 'ERZİN');
INSERT INTO public."Districts" VALUES (398, 37, 'HASSA');
INSERT INTO public."Districts" VALUES (399, 37, 'İSKENDERUN');
INSERT INTO public."Districts" VALUES (400, 37, 'KIRIKHAN');
INSERT INTO public."Districts" VALUES (401, 37, 'KUMLU');
INSERT INTO public."Districts" VALUES (402, 37, 'PAYAS');
INSERT INTO public."Districts" VALUES (403, 37, 'REYHANLI');
INSERT INTO public."Districts" VALUES (404, 37, 'SAMANDAĞ');
INSERT INTO public."Districts" VALUES (405, 37, 'YAYLADAĞI');
INSERT INTO public."Districts" VALUES (406, 38, 'ARALIK');
INSERT INTO public."Districts" VALUES (407, 38, 'KARAKOYUNLU');
INSERT INTO public."Districts" VALUES (408, 38, 'TUZLUCA');
INSERT INTO public."Districts" VALUES (409, 39, 'AKSU');
INSERT INTO public."Districts" VALUES (410, 39, 'ATABEY');
INSERT INTO public."Districts" VALUES (411, 39, 'EĞİRDİR');
INSERT INTO public."Districts" VALUES (412, 39, 'GELENDOST');
INSERT INTO public."Districts" VALUES (413, 39, 'GÖNEN');
INSERT INTO public."Districts" VALUES (414, 39, 'KEÇİBORLU');
INSERT INTO public."Districts" VALUES (415, 39, 'ŞARKİKARAAĞAÇ');
INSERT INTO public."Districts" VALUES (416, 39, 'SENİRKENT');
INSERT INTO public."Districts" VALUES (417, 39, 'SÜTÇÜLER');
INSERT INTO public."Districts" VALUES (418, 39, 'ULUBORLU');
INSERT INTO public."Districts" VALUES (419, 39, 'YALVAÇ');
INSERT INTO public."Districts" VALUES (420, 39, 'YENİŞARBADEMLİ');
INSERT INTO public."Districts" VALUES (421, 40, 'ADALAR');
INSERT INTO public."Districts" VALUES (422, 40, 'ARNAVUTKÖY');
INSERT INTO public."Districts" VALUES (423, 40, 'ATAŞEHİR');
INSERT INTO public."Districts" VALUES (424, 40, 'AVCILAR');
INSERT INTO public."Districts" VALUES (425, 40, 'BAĞCILAR');
INSERT INTO public."Districts" VALUES (426, 40, 'BAHÇELİEVLER');
INSERT INTO public."Districts" VALUES (427, 40, 'BAKIRKÖY');
INSERT INTO public."Districts" VALUES (428, 40, 'BAŞAKŞEHİR');
INSERT INTO public."Districts" VALUES (429, 40, 'BAYRAMPAŞA');
INSERT INTO public."Districts" VALUES (430, 40, 'BEŞİKTAŞ');
INSERT INTO public."Districts" VALUES (431, 40, 'BEYKOZ');
INSERT INTO public."Districts" VALUES (432, 40, 'BEYLİKDÜZÜ');
INSERT INTO public."Districts" VALUES (433, 40, 'BEYOĞLU');
INSERT INTO public."Districts" VALUES (434, 40, 'BÜYÜKÇEKMECE');
INSERT INTO public."Districts" VALUES (435, 40, 'ÇATALCA');
INSERT INTO public."Districts" VALUES (436, 40, 'ÇEKMEKÖY');
INSERT INTO public."Districts" VALUES (437, 40, 'ESENLER');
INSERT INTO public."Districts" VALUES (438, 40, 'ESENYURT');
INSERT INTO public."Districts" VALUES (439, 40, 'EYÜPSULTAN');
INSERT INTO public."Districts" VALUES (440, 40, 'FATİH');
INSERT INTO public."Districts" VALUES (441, 40, 'GAZİOSMANPAŞA');
INSERT INTO public."Districts" VALUES (442, 40, 'GÜNGÖREN');
INSERT INTO public."Districts" VALUES (443, 40, 'KADIKÖY');
INSERT INTO public."Districts" VALUES (444, 40, 'KAĞITHANE');
INSERT INTO public."Districts" VALUES (445, 40, 'KARTAL');
INSERT INTO public."Districts" VALUES (446, 40, 'KÜÇÜKÇEKMECE');
INSERT INTO public."Districts" VALUES (447, 40, 'MALTEPE');
INSERT INTO public."Districts" VALUES (448, 40, 'PENDİK');
INSERT INTO public."Districts" VALUES (449, 40, 'SANCAKTEPE');
INSERT INTO public."Districts" VALUES (450, 40, 'SARIYER');
INSERT INTO public."Districts" VALUES (451, 40, 'ŞİLE');
INSERT INTO public."Districts" VALUES (452, 40, 'SİLİVRİ');
INSERT INTO public."Districts" VALUES (453, 40, 'ŞİŞLİ');
INSERT INTO public."Districts" VALUES (454, 40, 'SULTANBEYLİ');
INSERT INTO public."Districts" VALUES (455, 40, 'SULTANGAZİ');
INSERT INTO public."Districts" VALUES (456, 40, 'TUZLA');
INSERT INTO public."Districts" VALUES (457, 40, 'ÜMRANİYE');
INSERT INTO public."Districts" VALUES (458, 40, 'ÜSKÜDAR');
INSERT INTO public."Districts" VALUES (459, 40, 'ZEYTİNBURNU');
INSERT INTO public."Districts" VALUES (460, 41, 'ALİAĞA');
INSERT INTO public."Districts" VALUES (461, 41, 'BALÇOVA');
INSERT INTO public."Districts" VALUES (462, 41, 'BAYINDIR');
INSERT INTO public."Districts" VALUES (463, 41, 'BAYRAKLI');
INSERT INTO public."Districts" VALUES (464, 41, 'BERGAMA');
INSERT INTO public."Districts" VALUES (465, 41, 'BEYDAĞ');
INSERT INTO public."Districts" VALUES (466, 41, 'BORNOVA');
INSERT INTO public."Districts" VALUES (467, 41, 'BUCA');
INSERT INTO public."Districts" VALUES (468, 41, 'ÇEŞME');
INSERT INTO public."Districts" VALUES (469, 41, 'ÇİĞLİ');
INSERT INTO public."Districts" VALUES (470, 41, 'DİKİLİ');
INSERT INTO public."Districts" VALUES (471, 41, 'FOÇA');
INSERT INTO public."Districts" VALUES (472, 41, 'GAZİEMİR');
INSERT INTO public."Districts" VALUES (473, 41, 'GÜZELBAHÇE');
INSERT INTO public."Districts" VALUES (474, 41, 'KARABAĞLAR');
INSERT INTO public."Districts" VALUES (475, 41, 'KARABURUN');
INSERT INTO public."Districts" VALUES (476, 41, 'KARŞIYAKA');
INSERT INTO public."Districts" VALUES (477, 41, 'KEMALPAŞA');
INSERT INTO public."Districts" VALUES (478, 41, 'KINIK');
INSERT INTO public."Districts" VALUES (479, 41, 'KİRAZ');
INSERT INTO public."Districts" VALUES (480, 41, 'KONAK');
INSERT INTO public."Districts" VALUES (481, 41, 'MENDERES');
INSERT INTO public."Districts" VALUES (482, 41, 'MENEMEN');
INSERT INTO public."Districts" VALUES (483, 41, 'NARLIDERE');
INSERT INTO public."Districts" VALUES (484, 41, 'ÖDEMİŞ');
INSERT INTO public."Districts" VALUES (485, 41, 'SEFERİHİSAR');
INSERT INTO public."Districts" VALUES (486, 41, 'SELÇUK');
INSERT INTO public."Districts" VALUES (487, 41, 'TİRE');
INSERT INTO public."Districts" VALUES (488, 41, 'TORBALI');
INSERT INTO public."Districts" VALUES (489, 41, 'URLA');
INSERT INTO public."Districts" VALUES (490, 42, 'AFŞİN');
INSERT INTO public."Districts" VALUES (491, 42, 'ANDIRIN');
INSERT INTO public."Districts" VALUES (492, 42, 'ÇAĞLAYANCERİT');
INSERT INTO public."Districts" VALUES (493, 42, 'DULKADİROĞLU');
INSERT INTO public."Districts" VALUES (494, 42, 'EKİNÖZÜ');
INSERT INTO public."Districts" VALUES (495, 42, 'ELBİSTAN');
INSERT INTO public."Districts" VALUES (496, 42, 'GÖKSUN');
INSERT INTO public."Districts" VALUES (497, 42, 'NURHAK');
INSERT INTO public."Districts" VALUES (498, 42, 'ONİKİŞUBAT');
INSERT INTO public."Districts" VALUES (499, 42, 'PAZARCIK');
INSERT INTO public."Districts" VALUES (500, 42, 'TÜRKOĞLU');
INSERT INTO public."Districts" VALUES (501, 43, 'EFLANİ');
INSERT INTO public."Districts" VALUES (502, 43, 'ESKİPAZAR');
INSERT INTO public."Districts" VALUES (503, 43, 'OVACIK');
INSERT INTO public."Districts" VALUES (504, 43, 'SAFRANBOLU');
INSERT INTO public."Districts" VALUES (505, 43, 'YENİCE');
INSERT INTO public."Districts" VALUES (506, 44, 'AYRANCI');
INSERT INTO public."Districts" VALUES (507, 44, 'BAŞYAYLA');
INSERT INTO public."Districts" VALUES (508, 44, 'ERMENEK');
INSERT INTO public."Districts" VALUES (509, 44, 'KAZIMKARABEKİR');
INSERT INTO public."Districts" VALUES (510, 44, 'SARIVELİLER');
INSERT INTO public."Districts" VALUES (511, 45, 'AKYAKA');
INSERT INTO public."Districts" VALUES (512, 45, 'ARPAÇAY');
INSERT INTO public."Districts" VALUES (513, 45, 'DİGOR');
INSERT INTO public."Districts" VALUES (514, 45, 'KAĞIZMAN');
INSERT INTO public."Districts" VALUES (515, 45, 'SARIKAMIŞ');
INSERT INTO public."Districts" VALUES (516, 45, 'SELİM');
INSERT INTO public."Districts" VALUES (517, 45, 'SUSUZ');
INSERT INTO public."Districts" VALUES (518, 46, 'ABANA');
INSERT INTO public."Districts" VALUES (519, 46, 'AĞLI');
INSERT INTO public."Districts" VALUES (520, 46, 'ARAÇ');
INSERT INTO public."Districts" VALUES (521, 46, 'AZDAVAY');
INSERT INTO public."Districts" VALUES (522, 46, 'BOZKURT');
INSERT INTO public."Districts" VALUES (523, 46, 'ÇATALZEYTİN');
INSERT INTO public."Districts" VALUES (524, 46, 'CİDE');
INSERT INTO public."Districts" VALUES (525, 46, 'DADAY');
INSERT INTO public."Districts" VALUES (526, 46, 'DEVREKANİ');
INSERT INTO public."Districts" VALUES (527, 46, 'DOĞANYURT');
INSERT INTO public."Districts" VALUES (528, 46, 'HANÖNÜ');
INSERT INTO public."Districts" VALUES (529, 46, 'İHSANGAZİ');
INSERT INTO public."Districts" VALUES (530, 46, 'İNEBOLU');
INSERT INTO public."Districts" VALUES (531, 46, 'KÜRE');
INSERT INTO public."Districts" VALUES (532, 46, 'PINARBAŞI');
INSERT INTO public."Districts" VALUES (533, 46, 'ŞENPAZAR');
INSERT INTO public."Districts" VALUES (534, 46, 'SEYDİLER');
INSERT INTO public."Districts" VALUES (535, 46, 'TAŞKÖPRÜ');
INSERT INTO public."Districts" VALUES (536, 46, 'TOSYA');
INSERT INTO public."Districts" VALUES (537, 47, 'AKKIŞLA');
INSERT INTO public."Districts" VALUES (538, 47, 'BÜNYAN');
INSERT INTO public."Districts" VALUES (539, 47, 'DEVELİ');
INSERT INTO public."Districts" VALUES (540, 47, 'FELAHİYE');
INSERT INTO public."Districts" VALUES (541, 47, 'HACILAR');
INSERT INTO public."Districts" VALUES (542, 47, 'İNCESU');
INSERT INTO public."Districts" VALUES (543, 47, 'KOCASİNAN');
INSERT INTO public."Districts" VALUES (544, 47, 'MELİKGAZİ');
INSERT INTO public."Districts" VALUES (545, 47, 'ÖZVATAN');
INSERT INTO public."Districts" VALUES (546, 47, 'PINARBAŞI');
INSERT INTO public."Districts" VALUES (547, 47, 'SARIOĞLAN');
INSERT INTO public."Districts" VALUES (548, 47, 'SARIZ');
INSERT INTO public."Districts" VALUES (549, 47, 'TALAS');
INSERT INTO public."Districts" VALUES (550, 47, 'TOMARZA');
INSERT INTO public."Districts" VALUES (551, 47, 'YAHYALI');
INSERT INTO public."Districts" VALUES (552, 47, 'YEŞİLHİSAR');
INSERT INTO public."Districts" VALUES (553, 48, 'ELBEYLİ');
INSERT INTO public."Districts" VALUES (554, 48, 'MUSABEYLİ');
INSERT INTO public."Districts" VALUES (555, 48, 'POLATELİ');
INSERT INTO public."Districts" VALUES (556, 49, 'BAHŞILI');
INSERT INTO public."Districts" VALUES (557, 49, 'BALIŞEYH');
INSERT INTO public."Districts" VALUES (558, 49, 'ÇELEBİ');
INSERT INTO public."Districts" VALUES (559, 49, 'DELİCE');
INSERT INTO public."Districts" VALUES (560, 49, 'KARAKEÇİLİ');
INSERT INTO public."Districts" VALUES (561, 49, 'KESKİN');
INSERT INTO public."Districts" VALUES (562, 49, 'SULAKYURT');
INSERT INTO public."Districts" VALUES (563, 49, 'YAHŞİHAN');
INSERT INTO public."Districts" VALUES (564, 50, 'BABAESKİ');
INSERT INTO public."Districts" VALUES (565, 50, 'DEMİRKÖY');
INSERT INTO public."Districts" VALUES (566, 50, 'KOFÇAZ');
INSERT INTO public."Districts" VALUES (567, 50, 'LÜLEBURGAZ');
INSERT INTO public."Districts" VALUES (568, 50, 'PEHLİVANKÖY');
INSERT INTO public."Districts" VALUES (569, 50, 'PINARHİSAR');
INSERT INTO public."Districts" VALUES (570, 50, 'VİZE');
INSERT INTO public."Districts" VALUES (571, 51, 'AKÇAKENT');
INSERT INTO public."Districts" VALUES (572, 51, 'AKPINAR');
INSERT INTO public."Districts" VALUES (573, 51, 'BOZTEPE');
INSERT INTO public."Districts" VALUES (574, 51, 'ÇİÇEKDAĞI');
INSERT INTO public."Districts" VALUES (575, 51, 'KAMAN');
INSERT INTO public."Districts" VALUES (576, 51, 'MUCUR');
INSERT INTO public."Districts" VALUES (577, 52, 'BAŞİSKELE');
INSERT INTO public."Districts" VALUES (578, 52, 'ÇAYIROVA');
INSERT INTO public."Districts" VALUES (579, 52, 'DARICA');
INSERT INTO public."Districts" VALUES (580, 52, 'DERİNCE');
INSERT INTO public."Districts" VALUES (581, 52, 'DİLOVASI');
INSERT INTO public."Districts" VALUES (582, 52, 'GEBZE');
INSERT INTO public."Districts" VALUES (583, 52, 'GÖLCÜK');
INSERT INTO public."Districts" VALUES (584, 52, 'İZMİT');
INSERT INTO public."Districts" VALUES (585, 52, 'KANDIRA');
INSERT INTO public."Districts" VALUES (586, 52, 'KARAMÜRSEL');
INSERT INTO public."Districts" VALUES (587, 52, 'KARTEPE');
INSERT INTO public."Districts" VALUES (588, 52, 'KÖRFEZ');
INSERT INTO public."Districts" VALUES (589, 53, 'AHIRLI');
INSERT INTO public."Districts" VALUES (590, 53, 'AKÖREN');
INSERT INTO public."Districts" VALUES (591, 53, 'AKŞEHİR');
INSERT INTO public."Districts" VALUES (592, 53, 'ALTINEKİN');
INSERT INTO public."Districts" VALUES (593, 53, 'BEYŞEHİR');
INSERT INTO public."Districts" VALUES (594, 53, 'BOZKIR');
INSERT INTO public."Districts" VALUES (595, 53, 'ÇELTİK');
INSERT INTO public."Districts" VALUES (596, 53, 'CİHANBEYLİ');
INSERT INTO public."Districts" VALUES (597, 53, 'ÇUMRA');
INSERT INTO public."Districts" VALUES (598, 53, 'DERBENT');
INSERT INTO public."Districts" VALUES (599, 53, 'DEREBUCAK');
INSERT INTO public."Districts" VALUES (600, 53, 'DOĞANHİSAR');
INSERT INTO public."Districts" VALUES (601, 53, 'EMİRGAZİ');
INSERT INTO public."Districts" VALUES (602, 53, 'EREĞLİ');
INSERT INTO public."Districts" VALUES (603, 53, 'GÜNEYSINIR');
INSERT INTO public."Districts" VALUES (604, 53, 'HADİM');
INSERT INTO public."Districts" VALUES (605, 53, 'HALKAPINAR');
INSERT INTO public."Districts" VALUES (606, 53, 'HÜYÜK');
INSERT INTO public."Districts" VALUES (607, 53, 'ILGIN');
INSERT INTO public."Districts" VALUES (608, 53, 'KADINHANI');
INSERT INTO public."Districts" VALUES (609, 53, 'KARAPINAR');
INSERT INTO public."Districts" VALUES (610, 53, 'KARATAY');
INSERT INTO public."Districts" VALUES (611, 53, 'KULU');
INSERT INTO public."Districts" VALUES (612, 53, 'MERAM');
INSERT INTO public."Districts" VALUES (613, 53, 'SARAYÖNÜ');
INSERT INTO public."Districts" VALUES (614, 53, 'SELÇUKLU');
INSERT INTO public."Districts" VALUES (615, 53, 'SEYDİŞEHİR');
INSERT INTO public."Districts" VALUES (616, 53, 'TAŞKENT');
INSERT INTO public."Districts" VALUES (617, 53, 'TUZLUKÇU');
INSERT INTO public."Districts" VALUES (618, 53, 'YALIHÜYÜK');
INSERT INTO public."Districts" VALUES (619, 53, 'YUNAK');
INSERT INTO public."Districts" VALUES (620, 54, 'ALTINTAŞ');
INSERT INTO public."Districts" VALUES (621, 54, 'ASLANAPA');
INSERT INTO public."Districts" VALUES (622, 54, 'ÇAVDARHİSAR');
INSERT INTO public."Districts" VALUES (623, 54, 'DOMANİÇ');
INSERT INTO public."Districts" VALUES (624, 54, 'DUMLUPINAR');
INSERT INTO public."Districts" VALUES (625, 54, 'EMET');
INSERT INTO public."Districts" VALUES (626, 54, 'GEDİZ');
INSERT INTO public."Districts" VALUES (627, 54, 'HİSARCIK');
INSERT INTO public."Districts" VALUES (628, 54, 'PAZARLAR');
INSERT INTO public."Districts" VALUES (629, 54, 'ŞAPHANE');
INSERT INTO public."Districts" VALUES (630, 54, 'SİMAV');
INSERT INTO public."Districts" VALUES (631, 54, 'TAVŞANLI');
INSERT INTO public."Districts" VALUES (632, 55, 'AKÇADAĞ');
INSERT INTO public."Districts" VALUES (633, 55, 'ARAPGİR');
INSERT INTO public."Districts" VALUES (634, 55, 'ARGUVAN');
INSERT INTO public."Districts" VALUES (635, 55, 'BATTALGAZİ');
INSERT INTO public."Districts" VALUES (636, 55, 'DARENDE');
INSERT INTO public."Districts" VALUES (637, 55, 'DOĞANŞEHİR');
INSERT INTO public."Districts" VALUES (638, 55, 'DOĞANYOL');
INSERT INTO public."Districts" VALUES (639, 55, 'HEKİMHAN');
INSERT INTO public."Districts" VALUES (640, 55, 'KALE');
INSERT INTO public."Districts" VALUES (641, 55, 'KULUNCAK');
INSERT INTO public."Districts" VALUES (642, 55, 'PÜTÜRGE');
INSERT INTO public."Districts" VALUES (643, 55, 'YAZIHAN');
INSERT INTO public."Districts" VALUES (644, 55, 'YEŞİLYURT');
INSERT INTO public."Districts" VALUES (645, 56, 'AHMETLİ');
INSERT INTO public."Districts" VALUES (646, 56, 'AKHİSAR');
INSERT INTO public."Districts" VALUES (647, 56, 'ALAŞEHİR');
INSERT INTO public."Districts" VALUES (648, 56, 'DEMİRCİ');
INSERT INTO public."Districts" VALUES (649, 56, 'GÖLMARMARA');
INSERT INTO public."Districts" VALUES (650, 56, 'GÖRDES');
INSERT INTO public."Districts" VALUES (651, 56, 'KIRKAĞAÇ');
INSERT INTO public."Districts" VALUES (652, 56, 'KÖPRÜBAŞI');
INSERT INTO public."Districts" VALUES (653, 56, 'KULA');
INSERT INTO public."Districts" VALUES (654, 56, 'SALİHLİ');
INSERT INTO public."Districts" VALUES (655, 56, 'SARIGÖL');
INSERT INTO public."Districts" VALUES (656, 56, 'SARUHANLI');
INSERT INTO public."Districts" VALUES (657, 56, 'ŞEHZADELER');
INSERT INTO public."Districts" VALUES (658, 56, 'SELENDİ');
INSERT INTO public."Districts" VALUES (659, 56, 'SOMA');
INSERT INTO public."Districts" VALUES (660, 56, 'TURGUTLU');
INSERT INTO public."Districts" VALUES (661, 56, 'YUNUSEMRE');
INSERT INTO public."Districts" VALUES (662, 57, 'ARTUKLU');
INSERT INTO public."Districts" VALUES (663, 57, 'DARGEÇİT');
INSERT INTO public."Districts" VALUES (664, 57, 'DERİK');
INSERT INTO public."Districts" VALUES (665, 57, 'KIZILTEPE');
INSERT INTO public."Districts" VALUES (666, 57, 'MAZIDAĞI');
INSERT INTO public."Districts" VALUES (667, 57, 'MİDYAT');
INSERT INTO public."Districts" VALUES (668, 57, 'NUSAYBİN');
INSERT INTO public."Districts" VALUES (669, 57, 'ÖMERLİ');
INSERT INTO public."Districts" VALUES (670, 57, 'SAVUR');
INSERT INTO public."Districts" VALUES (671, 57, 'YEŞİLLİ');
INSERT INTO public."Districts" VALUES (672, 58, 'AKDENİZ');
INSERT INTO public."Districts" VALUES (673, 58, 'ANAMUR');
INSERT INTO public."Districts" VALUES (674, 58, 'AYDINCIK');
INSERT INTO public."Districts" VALUES (675, 58, 'BOZYAZI');
INSERT INTO public."Districts" VALUES (676, 58, 'ÇAMLIYAYLA');
INSERT INTO public."Districts" VALUES (677, 58, 'ERDEMLİ');
INSERT INTO public."Districts" VALUES (678, 58, 'GÜLNAR');
INSERT INTO public."Districts" VALUES (679, 58, 'MEZİTLİ');
INSERT INTO public."Districts" VALUES (680, 58, 'MUT');
INSERT INTO public."Districts" VALUES (681, 58, 'SİLİFKE');
INSERT INTO public."Districts" VALUES (682, 58, 'TARSUS');
INSERT INTO public."Districts" VALUES (683, 58, 'TOROSLAR');
INSERT INTO public."Districts" VALUES (684, 58, 'YENİŞEHİR');
INSERT INTO public."Districts" VALUES (685, 59, 'BODRUM');
INSERT INTO public."Districts" VALUES (686, 59, 'DALAMAN');
INSERT INTO public."Districts" VALUES (687, 59, 'DATÇA');
INSERT INTO public."Districts" VALUES (688, 59, 'FETHİYE');
INSERT INTO public."Districts" VALUES (689, 59, 'KAVAKLIDERE');
INSERT INTO public."Districts" VALUES (690, 59, 'KÖYCEĞİZ');
INSERT INTO public."Districts" VALUES (691, 59, 'MARMARİS');
INSERT INTO public."Districts" VALUES (692, 59, 'MENTEŞE');
INSERT INTO public."Districts" VALUES (693, 59, 'MİLAS');
INSERT INTO public."Districts" VALUES (694, 59, 'ORTACA');
INSERT INTO public."Districts" VALUES (695, 59, 'SEYDİKEMER');
INSERT INTO public."Districts" VALUES (696, 59, 'ULA');
INSERT INTO public."Districts" VALUES (697, 59, 'YATAĞAN');
INSERT INTO public."Districts" VALUES (698, 60, 'BULANIK');
INSERT INTO public."Districts" VALUES (699, 60, 'HASKÖY');
INSERT INTO public."Districts" VALUES (700, 60, 'KORKUT');
INSERT INTO public."Districts" VALUES (701, 60, 'MALAZGİRT');
INSERT INTO public."Districts" VALUES (702, 60, 'VARTO');
INSERT INTO public."Districts" VALUES (703, 61, 'ACIGÖL');
INSERT INTO public."Districts" VALUES (704, 61, 'AVANOS');
INSERT INTO public."Districts" VALUES (705, 61, 'DERİNKUYU');
INSERT INTO public."Districts" VALUES (706, 61, 'GÜLŞEHİR');
INSERT INTO public."Districts" VALUES (707, 61, 'HACIBEKTAŞ');
INSERT INTO public."Districts" VALUES (708, 61, 'KOZAKLI');
INSERT INTO public."Districts" VALUES (709, 61, 'ÜRGÜP');
INSERT INTO public."Districts" VALUES (710, 62, 'ALTUNHİSAR');
INSERT INTO public."Districts" VALUES (711, 62, 'BOR');
INSERT INTO public."Districts" VALUES (712, 62, 'ÇAMARDI');
INSERT INTO public."Districts" VALUES (713, 62, 'ÇİFTLİK');
INSERT INTO public."Districts" VALUES (714, 62, 'ULUKIŞLA');
INSERT INTO public."Districts" VALUES (715, 63, 'AKKUŞ');
INSERT INTO public."Districts" VALUES (716, 63, 'ALTINORDU');
INSERT INTO public."Districts" VALUES (717, 63, 'AYBASTI');
INSERT INTO public."Districts" VALUES (718, 63, 'ÇAMAŞ');
INSERT INTO public."Districts" VALUES (719, 63, 'ÇATALPINAR');
INSERT INTO public."Districts" VALUES (720, 63, 'ÇAYBAŞI');
INSERT INTO public."Districts" VALUES (721, 63, 'FATSA');
INSERT INTO public."Districts" VALUES (722, 63, 'GÖLKÖY');
INSERT INTO public."Districts" VALUES (723, 63, 'GÜLYALI');
INSERT INTO public."Districts" VALUES (724, 63, 'GÜRGENTEPE');
INSERT INTO public."Districts" VALUES (725, 63, 'İKİZCE');
INSERT INTO public."Districts" VALUES (726, 63, 'KABADÜZ');
INSERT INTO public."Districts" VALUES (727, 63, 'KABATAŞ');
INSERT INTO public."Districts" VALUES (728, 63, 'KORGAN');
INSERT INTO public."Districts" VALUES (729, 63, 'KUMRU');
INSERT INTO public."Districts" VALUES (730, 63, 'MESUDİYE');
INSERT INTO public."Districts" VALUES (731, 63, 'PERŞEMBE');
INSERT INTO public."Districts" VALUES (732, 63, 'ULUBEY');
INSERT INTO public."Districts" VALUES (733, 63, 'ÜNYE');
INSERT INTO public."Districts" VALUES (734, 64, 'BAHÇE');
INSERT INTO public."Districts" VALUES (735, 64, 'DÜZİÇİ');
INSERT INTO public."Districts" VALUES (736, 64, 'HASANBEYLİ');
INSERT INTO public."Districts" VALUES (737, 64, 'KADİRLİ');
INSERT INTO public."Districts" VALUES (738, 64, 'SUMBAS');
INSERT INTO public."Districts" VALUES (739, 64, 'TOPRAKKALE');
INSERT INTO public."Districts" VALUES (740, 65, 'ARDEŞEN');
INSERT INTO public."Districts" VALUES (741, 65, 'ÇAMLIHEMŞİN');
INSERT INTO public."Districts" VALUES (742, 65, 'ÇAYELİ');
INSERT INTO public."Districts" VALUES (743, 65, 'DEREPAZARI');
INSERT INTO public."Districts" VALUES (744, 65, 'FINDIKLI');
INSERT INTO public."Districts" VALUES (745, 65, 'GÜNEYSU');
INSERT INTO public."Districts" VALUES (746, 65, 'HEMŞİN');
INSERT INTO public."Districts" VALUES (747, 65, 'İKİZDERE');
INSERT INTO public."Districts" VALUES (748, 65, 'İYİDERE');
INSERT INTO public."Districts" VALUES (749, 65, 'KALKANDERE');
INSERT INTO public."Districts" VALUES (750, 65, 'PAZAR');
INSERT INTO public."Districts" VALUES (751, 66, 'ADAPAZARI');
INSERT INTO public."Districts" VALUES (752, 66, 'AKYAZI');
INSERT INTO public."Districts" VALUES (753, 66, 'ARİFİYE');
INSERT INTO public."Districts" VALUES (754, 66, 'ERENLER');
INSERT INTO public."Districts" VALUES (755, 66, 'FERİZLİ');
INSERT INTO public."Districts" VALUES (756, 66, 'GEYVE');
INSERT INTO public."Districts" VALUES (757, 66, 'HENDEK');
INSERT INTO public."Districts" VALUES (758, 66, 'KARAPÜRÇEK');
INSERT INTO public."Districts" VALUES (759, 66, 'KARASU');
INSERT INTO public."Districts" VALUES (760, 66, 'KAYNARCA');
INSERT INTO public."Districts" VALUES (761, 66, 'KOCAALİ');
INSERT INTO public."Districts" VALUES (762, 66, 'PAMUKOVA');
INSERT INTO public."Districts" VALUES (763, 66, 'SAPANCA');
INSERT INTO public."Districts" VALUES (764, 66, 'SERDİVAN');
INSERT INTO public."Districts" VALUES (765, 66, 'SÖĞÜTLÜ');
INSERT INTO public."Districts" VALUES (766, 66, 'TARAKLI');
INSERT INTO public."Districts" VALUES (767, 67, '19 MAYIS');
INSERT INTO public."Districts" VALUES (768, 67, 'ALAÇAM');
INSERT INTO public."Districts" VALUES (769, 67, 'ASARCIK');
INSERT INTO public."Districts" VALUES (770, 67, 'ATAKUM');
INSERT INTO public."Districts" VALUES (771, 67, 'AYVACIK');
INSERT INTO public."Districts" VALUES (772, 67, 'BAFRA');
INSERT INTO public."Districts" VALUES (773, 67, 'CANİK');
INSERT INTO public."Districts" VALUES (774, 67, 'ÇARŞAMBA');
INSERT INTO public."Districts" VALUES (775, 67, 'HAVZA');
INSERT INTO public."Districts" VALUES (776, 67, 'İLKADIM');
INSERT INTO public."Districts" VALUES (777, 67, 'KAVAK');
INSERT INTO public."Districts" VALUES (778, 67, 'LADİK');
INSERT INTO public."Districts" VALUES (779, 67, 'SALIPAZARI');
INSERT INTO public."Districts" VALUES (780, 67, 'TEKKEKÖY');
INSERT INTO public."Districts" VALUES (781, 67, 'TERME');
INSERT INTO public."Districts" VALUES (782, 67, 'VEZİRKÖPRÜ');
INSERT INTO public."Districts" VALUES (783, 67, 'YAKAKENT');
INSERT INTO public."Districts" VALUES (784, 68, 'AKÇAKALE');
INSERT INTO public."Districts" VALUES (785, 68, 'BİRECİK');
INSERT INTO public."Districts" VALUES (786, 68, 'BOZOVA');
INSERT INTO public."Districts" VALUES (787, 68, 'CEYLANPINAR');
INSERT INTO public."Districts" VALUES (788, 68, 'EYYÜBİYE');
INSERT INTO public."Districts" VALUES (789, 68, 'HALFETİ');
INSERT INTO public."Districts" VALUES (790, 68, 'HALİLİYE');
INSERT INTO public."Districts" VALUES (791, 68, 'HARRAN');
INSERT INTO public."Districts" VALUES (792, 68, 'HİLVAN');
INSERT INTO public."Districts" VALUES (793, 68, 'KARAKÖPRÜ');
INSERT INTO public."Districts" VALUES (794, 68, 'SİVEREK');
INSERT INTO public."Districts" VALUES (795, 68, 'SURUÇ');
INSERT INTO public."Districts" VALUES (796, 68, 'VİRANŞEHİR');
INSERT INTO public."Districts" VALUES (797, 69, 'BAYKAN');
INSERT INTO public."Districts" VALUES (798, 69, 'ERUH');
INSERT INTO public."Districts" VALUES (799, 69, 'KURTALAN');
INSERT INTO public."Districts" VALUES (800, 69, 'PERVARİ');
INSERT INTO public."Districts" VALUES (801, 69, 'ŞİRVAN');
INSERT INTO public."Districts" VALUES (802, 69, 'TİLLO');
INSERT INTO public."Districts" VALUES (803, 70, 'AYANCIK');
INSERT INTO public."Districts" VALUES (804, 70, 'BOYABAT');
INSERT INTO public."Districts" VALUES (805, 70, 'DİKMEN');
INSERT INTO public."Districts" VALUES (806, 70, 'DURAĞAN');
INSERT INTO public."Districts" VALUES (807, 70, 'ERFELEK');
INSERT INTO public."Districts" VALUES (808, 70, 'GERZE');
INSERT INTO public."Districts" VALUES (809, 70, 'SARAYDÜZÜ');
INSERT INTO public."Districts" VALUES (810, 70, 'TÜRKELİ');
INSERT INTO public."Districts" VALUES (811, 71, 'BEYTÜŞŞEBAP');
INSERT INTO public."Districts" VALUES (812, 71, 'CİZRE');
INSERT INTO public."Districts" VALUES (813, 71, 'GÜÇLÜKONAK');
INSERT INTO public."Districts" VALUES (814, 71, 'İDİL');
INSERT INTO public."Districts" VALUES (815, 71, 'SİLOPİ');
INSERT INTO public."Districts" VALUES (816, 71, 'ULUDERE');
INSERT INTO public."Districts" VALUES (817, 72, 'AKINCILAR');
INSERT INTO public."Districts" VALUES (818, 72, 'ALTINYAYLA');
INSERT INTO public."Districts" VALUES (819, 72, 'DİVRİĞİ');
INSERT INTO public."Districts" VALUES (820, 72, 'DOĞANŞAR');
INSERT INTO public."Districts" VALUES (821, 72, 'GEMEREK');
INSERT INTO public."Districts" VALUES (822, 72, 'GÖLOVA');
INSERT INTO public."Districts" VALUES (823, 72, 'GÜRÜN');
INSERT INTO public."Districts" VALUES (824, 72, 'HAFİK');
INSERT INTO public."Districts" VALUES (825, 72, 'İMRANLI');
INSERT INTO public."Districts" VALUES (826, 72, 'KANGAL');
INSERT INTO public."Districts" VALUES (827, 72, 'KOYULHİSAR');
INSERT INTO public."Districts" VALUES (828, 72, 'ŞARKIŞLA');
INSERT INTO public."Districts" VALUES (829, 72, 'SUŞEHRİ');
INSERT INTO public."Districts" VALUES (830, 72, 'ULAŞ');
INSERT INTO public."Districts" VALUES (831, 72, 'YILDIZELİ');
INSERT INTO public."Districts" VALUES (832, 72, 'ZARA');
INSERT INTO public."Districts" VALUES (833, 73, 'ÇERKEZKÖY');
INSERT INTO public."Districts" VALUES (834, 73, 'ÇORLU');
INSERT INTO public."Districts" VALUES (835, 73, 'ERGENE');
INSERT INTO public."Districts" VALUES (836, 73, 'HAYRABOLU');
INSERT INTO public."Districts" VALUES (837, 73, 'KAPAKLI');
INSERT INTO public."Districts" VALUES (838, 73, 'MALKARA');
INSERT INTO public."Districts" VALUES (839, 73, 'MARMARAEREĞLİSİ');
INSERT INTO public."Districts" VALUES (840, 73, 'MURATLI');
INSERT INTO public."Districts" VALUES (841, 73, 'SARAY');
INSERT INTO public."Districts" VALUES (842, 73, 'ŞARKÖY');
INSERT INTO public."Districts" VALUES (843, 73, 'SÜLEYMANPAŞA');
INSERT INTO public."Districts" VALUES (844, 74, 'ALMUS');
INSERT INTO public."Districts" VALUES (845, 74, 'ARTOVA');
INSERT INTO public."Districts" VALUES (846, 74, 'BAŞÇİFTLİK');
INSERT INTO public."Districts" VALUES (847, 74, 'ERBAA');
INSERT INTO public."Districts" VALUES (848, 74, 'NİKSAR');
INSERT INTO public."Districts" VALUES (849, 74, 'PAZAR');
INSERT INTO public."Districts" VALUES (850, 74, 'REŞADİYE');
INSERT INTO public."Districts" VALUES (851, 74, 'SULUSARAY');
INSERT INTO public."Districts" VALUES (852, 74, 'TURHAL');
INSERT INTO public."Districts" VALUES (853, 74, 'YEŞİLYURT');
INSERT INTO public."Districts" VALUES (854, 74, 'ZİLE');
INSERT INTO public."Districts" VALUES (855, 75, 'AKÇAABAT');
INSERT INTO public."Districts" VALUES (856, 75, 'ARAKLI');
INSERT INTO public."Districts" VALUES (857, 75, 'ARSİN');
INSERT INTO public."Districts" VALUES (858, 75, 'BEŞİKDÜZÜ');
INSERT INTO public."Districts" VALUES (859, 75, 'ÇARŞIBAŞI');
INSERT INTO public."Districts" VALUES (860, 75, 'ÇAYKARA');
INSERT INTO public."Districts" VALUES (861, 75, 'DERNEKPAZARI');
INSERT INTO public."Districts" VALUES (862, 75, 'DÜZKÖY');
INSERT INTO public."Districts" VALUES (863, 75, 'HAYRAT');
INSERT INTO public."Districts" VALUES (864, 75, 'KÖPRÜBAŞI');
INSERT INTO public."Districts" VALUES (865, 75, 'MAÇKA');
INSERT INTO public."Districts" VALUES (866, 75, 'OF');
INSERT INTO public."Districts" VALUES (867, 75, 'ORTAHİSAR');
INSERT INTO public."Districts" VALUES (868, 75, 'ŞALPAZARI');
INSERT INTO public."Districts" VALUES (869, 75, 'SÜRMENE');
INSERT INTO public."Districts" VALUES (870, 75, 'TONYA');
INSERT INTO public."Districts" VALUES (871, 75, 'VAKFIKEBİR');
INSERT INTO public."Districts" VALUES (872, 75, 'YOMRA');
INSERT INTO public."Districts" VALUES (873, 76, 'ÇEMİŞGEZEK');
INSERT INTO public."Districts" VALUES (874, 76, 'HOZAT');
INSERT INTO public."Districts" VALUES (875, 76, 'MAZGİRT');
INSERT INTO public."Districts" VALUES (876, 76, 'NAZIMİYE');
INSERT INTO public."Districts" VALUES (877, 76, 'OVACIK');
INSERT INTO public."Districts" VALUES (878, 76, 'PERTEK');
INSERT INTO public."Districts" VALUES (879, 76, 'PÜLÜMÜR');
INSERT INTO public."Districts" VALUES (880, 77, 'BANAZ');
INSERT INTO public."Districts" VALUES (881, 77, 'EŞME');
INSERT INTO public."Districts" VALUES (882, 77, 'KARAHALLI');
INSERT INTO public."Districts" VALUES (883, 77, 'SİVASLI');
INSERT INTO public."Districts" VALUES (884, 77, 'ULUBEY');
INSERT INTO public."Districts" VALUES (885, 78, 'BAHÇESARAY');
INSERT INTO public."Districts" VALUES (886, 78, 'BAŞKALE');
INSERT INTO public."Districts" VALUES (887, 78, 'ÇALDIRAN');
INSERT INTO public."Districts" VALUES (888, 78, 'ÇATAK');
INSERT INTO public."Districts" VALUES (889, 78, 'EDREMİT');
INSERT INTO public."Districts" VALUES (890, 78, 'ERCİŞ');
INSERT INTO public."Districts" VALUES (891, 78, 'GEVAŞ');
INSERT INTO public."Districts" VALUES (892, 78, 'GÜRPINAR');
INSERT INTO public."Districts" VALUES (893, 78, 'İPEKYOLU');
INSERT INTO public."Districts" VALUES (894, 78, 'MURADİYE');
INSERT INTO public."Districts" VALUES (895, 78, 'ÖZALP');
INSERT INTO public."Districts" VALUES (896, 78, 'SARAY');
INSERT INTO public."Districts" VALUES (897, 78, 'TUŞBA');
INSERT INTO public."Districts" VALUES (898, 79, 'ALTINOVA');
INSERT INTO public."Districts" VALUES (899, 79, 'ARMUTLU');
INSERT INTO public."Districts" VALUES (900, 79, 'ÇİFTLİKKÖY');
INSERT INTO public."Districts" VALUES (901, 79, 'ÇINARCIK');
INSERT INTO public."Districts" VALUES (902, 79, 'TERMAL');
INSERT INTO public."Districts" VALUES (903, 80, 'AKDAĞMADENİ');
INSERT INTO public."Districts" VALUES (904, 80, 'AYDINCIK');
INSERT INTO public."Districts" VALUES (905, 80, 'BOĞAZLIYAN');
INSERT INTO public."Districts" VALUES (906, 80, 'ÇANDIR');
INSERT INTO public."Districts" VALUES (907, 80, 'ÇAYIRALAN');
INSERT INTO public."Districts" VALUES (908, 80, 'ÇEKEREK');
INSERT INTO public."Districts" VALUES (909, 80, 'KADIŞEHRİ');
INSERT INTO public."Districts" VALUES (910, 80, 'SARAYKENT');
INSERT INTO public."Districts" VALUES (911, 80, 'SARIKAYA');
INSERT INTO public."Districts" VALUES (912, 80, 'ŞEFAATLİ');
INSERT INTO public."Districts" VALUES (913, 80, 'SORGUN');
INSERT INTO public."Districts" VALUES (914, 80, 'YENİFAKILI');
INSERT INTO public."Districts" VALUES (915, 80, 'YERKÖY');
INSERT INTO public."Districts" VALUES (916, 81, 'ALAPLI');
INSERT INTO public."Districts" VALUES (917, 81, 'ÇAYCUMA');
INSERT INTO public."Districts" VALUES (918, 81, 'DEVREK');
INSERT INTO public."Districts" VALUES (919, 81, 'EREĞLİ');
INSERT INTO public."Districts" VALUES (920, 81, 'GÖKÇEBEY');
INSERT INTO public."Districts" VALUES (921, 81, 'KİLİMLİ');
INSERT INTO public."Districts" VALUES (922, 81, 'KOZLU');


--
-- TOC entry 3339 (class 0 OID 0)
-- Dependencies: 214
-- Name: Cities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cities_Id_seq"', 81, true);


--
-- TOC entry 3340 (class 0 OID 0)
-- Dependencies: 216
-- Name: Districts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Districts_Id_seq"', 922, true);


--
-- TOC entry 3182 (class 2606 OID 16394)
-- Name: Cities PK_Cities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "PK_Cities" PRIMARY KEY ("Id");


--
-- TOC entry 3185 (class 2606 OID 16400)
-- Name: Districts PK_Districts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Districts"
    ADD CONSTRAINT "PK_Districts" PRIMARY KEY ("Id");


--
-- TOC entry 3183 (class 1259 OID 16406)
-- Name: IX_Districts_CityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Districts_CityId" ON public."Districts" USING btree ("CityId");


--
-- TOC entry 3186 (class 2606 OID 16401)
-- Name: Districts FK_Districts_Cities_CityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Districts"
    ADD CONSTRAINT "FK_Districts_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES public."Cities"("Id") ON DELETE CASCADE;


-- Completed on 2023-02-09 16:25:16

--
-- PostgreSQL database dump complete
--

