--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Debian 15.1-1.pgdg110+1)
-- Dumped by pg_dump version 15.1

-- Started on 2023-02-09 17:37:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3338 (class 1262 OID 16427)
-- Name: Turkiye; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Turkiye" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE "Turkiye" OWNER TO postgres;

\connect "Turkiye"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16429)
-- Name: Cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cities" (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Abbreviation" character varying(10) NOT NULL,
    "DisplayOrder" integer NOT NULL
);


ALTER TABLE public."Cities" OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16428)
-- Name: Cities_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cities" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cities_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16435)
-- Name: Districts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Districts" (
    "Id" integer NOT NULL,
    "CityId" integer NOT NULL,
    "Name" character varying(100) NOT NULL
);


ALTER TABLE public."Districts" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16434)
-- Name: Districts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Districts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Districts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3330 (class 0 OID 16429)
-- Dependencies: 215
-- Data for Name: Cities; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Cities" VALUES (1, 'ADANA', '01', 1);
INSERT INTO public."Cities" VALUES (2, 'ADIYAMAN', '02', 2);
INSERT INTO public."Cities" VALUES (3, 'AFYONKARAHİSAR', '03', 3);
INSERT INTO public."Cities" VALUES (4, 'AĞRI', '04', 4);
INSERT INTO public."Cities" VALUES (5, 'AMASYA', '05', 5);
INSERT INTO public."Cities" VALUES (6, 'ANKARA', '06', 6);
INSERT INTO public."Cities" VALUES (7, 'ANTALYA', '07', 7);
INSERT INTO public."Cities" VALUES (8, 'ARTVİN', '08', 8);
INSERT INTO public."Cities" VALUES (9, 'AYDIN', '09', 9);
INSERT INTO public."Cities" VALUES (10, 'BALIKESİR', '10', 10);
INSERT INTO public."Cities" VALUES (11, 'BİLECİK', '11', 11);
INSERT INTO public."Cities" VALUES (12, 'BİNGÖL', '12', 12);
INSERT INTO public."Cities" VALUES (13, 'BİTLİS', '13', 13);
INSERT INTO public."Cities" VALUES (14, 'BOLU', '14', 14);
INSERT INTO public."Cities" VALUES (15, 'BURDUR', '15', 15);
INSERT INTO public."Cities" VALUES (16, 'BURSA', '16', 16);
INSERT INTO public."Cities" VALUES (17, 'ÇANAKKALE', '17', 17);
INSERT INTO public."Cities" VALUES (18, 'ÇANKIRI', '18', 18);
INSERT INTO public."Cities" VALUES (19, 'ÇORUM', '19', 19);
INSERT INTO public."Cities" VALUES (20, 'DENİZLİ', '20', 20);
INSERT INTO public."Cities" VALUES (21, 'DİYARBAKIR', '21', 21);
INSERT INTO public."Cities" VALUES (22, 'EDİRNE', '22', 22);
INSERT INTO public."Cities" VALUES (23, 'ELAZIĞ', '23', 23);
INSERT INTO public."Cities" VALUES (24, 'ERZİNCAN', '24', 24);
INSERT INTO public."Cities" VALUES (25, 'ERZURUM', '25', 25);
INSERT INTO public."Cities" VALUES (26, 'ESKİŞEHİR', '26', 26);
INSERT INTO public."Cities" VALUES (27, 'GAZİANTEP', '27', 27);
INSERT INTO public."Cities" VALUES (28, 'GİRESUN', '28', 28);
INSERT INTO public."Cities" VALUES (29, 'GÜMÜŞHANE', '29', 29);
INSERT INTO public."Cities" VALUES (30, 'HAKKARİ', '30', 30);
INSERT INTO public."Cities" VALUES (31, 'HATAY', '31', 31);
INSERT INTO public."Cities" VALUES (32, 'ISPARTA', '32', 32);
INSERT INTO public."Cities" VALUES (33, 'MERSİN', '33', 33);
INSERT INTO public."Cities" VALUES (34, 'İSTANBUL', '34', 34);
INSERT INTO public."Cities" VALUES (35, 'İZMİR', '35', 35);
INSERT INTO public."Cities" VALUES (36, 'KARS', '36', 36);
INSERT INTO public."Cities" VALUES (37, 'KASTAMONU', '37', 37);
INSERT INTO public."Cities" VALUES (38, 'KAYSERİ', '38', 38);
INSERT INTO public."Cities" VALUES (39, 'KIRKLARELİ', '39', 39);
INSERT INTO public."Cities" VALUES (40, 'KIRŞEHİR', '40', 40);
INSERT INTO public."Cities" VALUES (41, 'KOCAELİ', '41', 41);
INSERT INTO public."Cities" VALUES (42, 'KONYA', '42', 42);
INSERT INTO public."Cities" VALUES (43, 'KÜTAHYA', '43', 43);
INSERT INTO public."Cities" VALUES (44, 'MALATYA', '44', 44);
INSERT INTO public."Cities" VALUES (45, 'MANİSA', '45', 45);
INSERT INTO public."Cities" VALUES (46, 'KAHRAMANMARAŞ', '46', 46);
INSERT INTO public."Cities" VALUES (47, 'MARDİN', '47', 47);
INSERT INTO public."Cities" VALUES (48, 'MUĞLA', '48', 48);
INSERT INTO public."Cities" VALUES (49, 'MUŞ', '49', 49);
INSERT INTO public."Cities" VALUES (50, 'NEVŞEHİR', '50', 50);
INSERT INTO public."Cities" VALUES (51, 'NİĞDE', '51', 51);
INSERT INTO public."Cities" VALUES (52, 'ORDU', '52', 52);
INSERT INTO public."Cities" VALUES (53, 'RİZE', '53', 53);
INSERT INTO public."Cities" VALUES (54, 'SAKARYA', '54', 54);
INSERT INTO public."Cities" VALUES (55, 'SAMSUN', '55', 55);
INSERT INTO public."Cities" VALUES (56, 'SİİRT', '56', 56);
INSERT INTO public."Cities" VALUES (57, 'SİNOP', '57', 57);
INSERT INTO public."Cities" VALUES (58, 'SİVAS', '58', 58);
INSERT INTO public."Cities" VALUES (59, 'TEKİRDAĞ', '59', 59);
INSERT INTO public."Cities" VALUES (60, 'TOKAT', '60', 60);
INSERT INTO public."Cities" VALUES (61, 'TRABZON', '61', 61);
INSERT INTO public."Cities" VALUES (62, 'TUNCELİ', '62', 62);
INSERT INTO public."Cities" VALUES (63, 'ŞANLIURFA', '63', 63);
INSERT INTO public."Cities" VALUES (64, 'UŞAK', '64', 64);
INSERT INTO public."Cities" VALUES (65, 'VAN', '65', 65);
INSERT INTO public."Cities" VALUES (66, 'YOZGAT', '66', 66);
INSERT INTO public."Cities" VALUES (67, 'ZONGULDAK', '67', 67);
INSERT INTO public."Cities" VALUES (68, 'AKSARAY', '68', 68);
INSERT INTO public."Cities" VALUES (69, 'BAYBURT', '69', 69);
INSERT INTO public."Cities" VALUES (70, 'KARAMAN', '70', 70);
INSERT INTO public."Cities" VALUES (71, 'KIRIKKALE', '71', 71);
INSERT INTO public."Cities" VALUES (72, 'BATMAN', '72', 72);
INSERT INTO public."Cities" VALUES (73, 'ŞIRNAK', '73', 73);
INSERT INTO public."Cities" VALUES (74, 'BARTIN', '74', 74);
INSERT INTO public."Cities" VALUES (75, 'ARDAHAN', '75', 75);
INSERT INTO public."Cities" VALUES (76, 'IĞDIR', '76', 76);
INSERT INTO public."Cities" VALUES (77, 'YALOVA', '77', 77);
INSERT INTO public."Cities" VALUES (78, 'KARABÜK', '78', 78);
INSERT INTO public."Cities" VALUES (79, 'KİLİS', '79', 79);
INSERT INTO public."Cities" VALUES (80, 'OSMANİYE', '80', 80);
INSERT INTO public."Cities" VALUES (81, 'DÜZCE', '81', 81);


--
-- TOC entry 3332 (class 0 OID 16435)
-- Dependencies: 217
-- Data for Name: Districts; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Districts" VALUES (1, 1, 'ALADAĞ');
INSERT INTO public."Districts" VALUES (2, 1, 'CEYHAN');
INSERT INTO public."Districts" VALUES (3, 1, 'ÇUKUROVA');
INSERT INTO public."Districts" VALUES (4, 1, 'FEKE');
INSERT INTO public."Districts" VALUES (5, 1, 'İMAMOĞLU');
INSERT INTO public."Districts" VALUES (6, 1, 'KARAİSALI');
INSERT INTO public."Districts" VALUES (7, 1, 'KARATAŞ');
INSERT INTO public."Districts" VALUES (8, 1, 'KOZAN');
INSERT INTO public."Districts" VALUES (9, 1, 'POZANTI');
INSERT INTO public."Districts" VALUES (10, 1, 'SAİMBEYLİ');
INSERT INTO public."Districts" VALUES (11, 1, 'SARIÇAM');
INSERT INTO public."Districts" VALUES (12, 1, 'SEYHAN');
INSERT INTO public."Districts" VALUES (13, 1, 'TUFANBEYLİ');
INSERT INTO public."Districts" VALUES (14, 1, 'YUMURTALIK');
INSERT INTO public."Districts" VALUES (15, 1, 'YÜREĞİR');
INSERT INTO public."Districts" VALUES (16, 2, 'BESNİ');
INSERT INTO public."Districts" VALUES (17, 2, 'ÇELİKHAN');
INSERT INTO public."Districts" VALUES (18, 2, 'GERGER');
INSERT INTO public."Districts" VALUES (19, 2, 'GÖLBAŞI');
INSERT INTO public."Districts" VALUES (20, 2, 'KAHTA');
INSERT INTO public."Districts" VALUES (21, 2, 'SAMSAT');
INSERT INTO public."Districts" VALUES (22, 2, 'SİNCİK');
INSERT INTO public."Districts" VALUES (23, 2, 'TUT');
INSERT INTO public."Districts" VALUES (24, 3, 'BAŞMAKÇI');
INSERT INTO public."Districts" VALUES (25, 3, 'BAYAT');
INSERT INTO public."Districts" VALUES (26, 3, 'BOLVADİN');
INSERT INTO public."Districts" VALUES (27, 3, 'ÇAY');
INSERT INTO public."Districts" VALUES (28, 3, 'ÇOBANLAR');
INSERT INTO public."Districts" VALUES (29, 3, 'DAZKIRI');
INSERT INTO public."Districts" VALUES (30, 3, 'DİNAR');
INSERT INTO public."Districts" VALUES (31, 3, 'EMİRDAĞ');
INSERT INTO public."Districts" VALUES (32, 3, 'EVCİLER');
INSERT INTO public."Districts" VALUES (33, 3, 'HOCALAR');
INSERT INTO public."Districts" VALUES (34, 3, 'İHSANİYE');
INSERT INTO public."Districts" VALUES (35, 3, 'İSCEHİSAR');
INSERT INTO public."Districts" VALUES (36, 3, 'KIZILÖREN');
INSERT INTO public."Districts" VALUES (37, 3, 'SANDIKLI');
INSERT INTO public."Districts" VALUES (38, 3, 'SİNANPAŞA');
INSERT INTO public."Districts" VALUES (39, 3, 'ŞUHUT');
INSERT INTO public."Districts" VALUES (40, 3, 'SULTANDAĞI');
INSERT INTO public."Districts" VALUES (41, 4, 'DİYADİN');
INSERT INTO public."Districts" VALUES (42, 4, 'DOĞUBAYAZIT');
INSERT INTO public."Districts" VALUES (43, 4, 'ELEŞKİRT');
INSERT INTO public."Districts" VALUES (44, 4, 'HAMUR');
INSERT INTO public."Districts" VALUES (45, 4, 'PATNOS');
INSERT INTO public."Districts" VALUES (46, 4, 'TAŞLIÇAY');
INSERT INTO public."Districts" VALUES (47, 4, 'TUTAK');
INSERT INTO public."Districts" VALUES (48, 5, 'GÖYNÜCEK');
INSERT INTO public."Districts" VALUES (49, 5, 'GÜMÜŞHACIKÖY');
INSERT INTO public."Districts" VALUES (50, 5, 'HAMAMÖZÜ');
INSERT INTO public."Districts" VALUES (51, 5, 'MERZİFON');
INSERT INTO public."Districts" VALUES (52, 5, 'SULUOVA');
INSERT INTO public."Districts" VALUES (53, 5, 'TAŞOVA');
INSERT INTO public."Districts" VALUES (54, 6, 'AKYURT');
INSERT INTO public."Districts" VALUES (55, 6, 'ALTINDAĞ');
INSERT INTO public."Districts" VALUES (56, 6, 'AYAŞ');
INSERT INTO public."Districts" VALUES (57, 6, 'BALA');
INSERT INTO public."Districts" VALUES (58, 6, 'BEYPAZARI');
INSERT INTO public."Districts" VALUES (59, 6, 'ÇAMLIDERE');
INSERT INTO public."Districts" VALUES (60, 6, 'ÇANKAYA');
INSERT INTO public."Districts" VALUES (61, 6, 'ÇUBUK');
INSERT INTO public."Districts" VALUES (62, 6, 'ELMADAĞ');
INSERT INTO public."Districts" VALUES (63, 6, 'ETİMESGUT');
INSERT INTO public."Districts" VALUES (64, 6, 'EVREN');
INSERT INTO public."Districts" VALUES (65, 6, 'GÖLBAŞI');
INSERT INTO public."Districts" VALUES (66, 6, 'GÜDÜL');
INSERT INTO public."Districts" VALUES (67, 6, 'HAYMANA');
INSERT INTO public."Districts" VALUES (68, 6, 'KAHRAMANKAZAN');
INSERT INTO public."Districts" VALUES (69, 6, 'KALECİK');
INSERT INTO public."Districts" VALUES (70, 6, 'KEÇİÖREN');
INSERT INTO public."Districts" VALUES (71, 6, 'KIZILCAHAMAM');
INSERT INTO public."Districts" VALUES (72, 6, 'MAMAK');
INSERT INTO public."Districts" VALUES (73, 6, 'NALLIHAN');
INSERT INTO public."Districts" VALUES (74, 6, 'POLATLI');
INSERT INTO public."Districts" VALUES (75, 6, 'PURSAKLAR');
INSERT INTO public."Districts" VALUES (76, 6, 'ŞEREFLİKOÇHİSAR');
INSERT INTO public."Districts" VALUES (77, 6, 'SİNCAN');
INSERT INTO public."Districts" VALUES (78, 6, 'YENİMAHALLE');
INSERT INTO public."Districts" VALUES (79, 7, 'AKSEKİ');
INSERT INTO public."Districts" VALUES (80, 7, 'AKSU');
INSERT INTO public."Districts" VALUES (81, 7, 'ALANYA');
INSERT INTO public."Districts" VALUES (82, 7, 'DEMRE');
INSERT INTO public."Districts" VALUES (83, 7, 'DÖŞEMEALTI');
INSERT INTO public."Districts" VALUES (84, 7, 'ELMALI');
INSERT INTO public."Districts" VALUES (85, 7, 'FİNİKE');
INSERT INTO public."Districts" VALUES (86, 7, 'GAZİPAŞA');
INSERT INTO public."Districts" VALUES (87, 7, 'GÜNDOĞMUŞ');
INSERT INTO public."Districts" VALUES (88, 7, 'İBRADI');
INSERT INTO public."Districts" VALUES (89, 7, 'KAŞ');
INSERT INTO public."Districts" VALUES (90, 7, 'KEMER');
INSERT INTO public."Districts" VALUES (91, 7, 'KEPEZ');
INSERT INTO public."Districts" VALUES (92, 7, 'KONYAALTI');
INSERT INTO public."Districts" VALUES (93, 7, 'KORKUTELİ');
INSERT INTO public."Districts" VALUES (94, 7, 'KUMLUCA');
INSERT INTO public."Districts" VALUES (95, 7, 'MANAVGAT');
INSERT INTO public."Districts" VALUES (96, 7, 'MURATPAŞA');
INSERT INTO public."Districts" VALUES (97, 7, 'SERİK');
INSERT INTO public."Districts" VALUES (98, 8, 'ARDANUÇ');
INSERT INTO public."Districts" VALUES (99, 8, 'ARHAVİ');
INSERT INTO public."Districts" VALUES (100, 8, 'BORÇKA');
INSERT INTO public."Districts" VALUES (101, 8, 'HOPA');
INSERT INTO public."Districts" VALUES (102, 8, 'KEMALPAŞA');
INSERT INTO public."Districts" VALUES (103, 8, 'MURGUL');
INSERT INTO public."Districts" VALUES (104, 8, 'ŞAVŞAT');
INSERT INTO public."Districts" VALUES (105, 8, 'YUSUFELİ');
INSERT INTO public."Districts" VALUES (106, 9, 'BOZDOĞAN');
INSERT INTO public."Districts" VALUES (107, 9, 'BUHARKENT');
INSERT INTO public."Districts" VALUES (108, 9, 'ÇİNE');
INSERT INTO public."Districts" VALUES (109, 9, 'DİDİM');
INSERT INTO public."Districts" VALUES (110, 9, 'EFELER');
INSERT INTO public."Districts" VALUES (111, 9, 'GERMENCİK');
INSERT INTO public."Districts" VALUES (112, 9, 'İNCİRLİOVA');
INSERT INTO public."Districts" VALUES (113, 9, 'KARACASU');
INSERT INTO public."Districts" VALUES (114, 9, 'KARPUZLU');
INSERT INTO public."Districts" VALUES (115, 9, 'KOÇARLI');
INSERT INTO public."Districts" VALUES (116, 9, 'KÖŞK');
INSERT INTO public."Districts" VALUES (117, 9, 'KUŞADASI');
INSERT INTO public."Districts" VALUES (118, 9, 'KUYUCAK');
INSERT INTO public."Districts" VALUES (119, 9, 'NAZİLLİ');
INSERT INTO public."Districts" VALUES (120, 9, 'SÖKE');
INSERT INTO public."Districts" VALUES (121, 9, 'SULTANHİSAR');
INSERT INTO public."Districts" VALUES (122, 9, 'YENİPAZAR');
INSERT INTO public."Districts" VALUES (123, 10, 'ALTIEYLÜL');
INSERT INTO public."Districts" VALUES (124, 10, 'AYVALIK');
INSERT INTO public."Districts" VALUES (125, 10, 'BALYA');
INSERT INTO public."Districts" VALUES (126, 10, 'BANDIRMA');
INSERT INTO public."Districts" VALUES (127, 10, 'BİGADİÇ');
INSERT INTO public."Districts" VALUES (128, 10, 'BURHANİYE');
INSERT INTO public."Districts" VALUES (129, 10, 'DURSUNBEY');
INSERT INTO public."Districts" VALUES (130, 10, 'EDREMİT');
INSERT INTO public."Districts" VALUES (131, 10, 'ERDEK');
INSERT INTO public."Districts" VALUES (132, 10, 'GÖMEÇ');
INSERT INTO public."Districts" VALUES (133, 10, 'GÖNEN');
INSERT INTO public."Districts" VALUES (134, 10, 'HAVRAN');
INSERT INTO public."Districts" VALUES (135, 10, 'İVRİNDİ');
INSERT INTO public."Districts" VALUES (136, 10, 'KARESİ');
INSERT INTO public."Districts" VALUES (137, 10, 'KEPSUT');
INSERT INTO public."Districts" VALUES (138, 10, 'MANYAS');
INSERT INTO public."Districts" VALUES (139, 10, 'MARMARA');
INSERT INTO public."Districts" VALUES (140, 10, 'SAVAŞTEPE');
INSERT INTO public."Districts" VALUES (141, 10, 'SINDIRGI');
INSERT INTO public."Districts" VALUES (142, 10, 'SUSURLUK');
INSERT INTO public."Districts" VALUES (143, 11, 'BOZÜYÜK');
INSERT INTO public."Districts" VALUES (144, 11, 'GÖLPAZARI');
INSERT INTO public."Districts" VALUES (145, 11, 'İNHİSAR');
INSERT INTO public."Districts" VALUES (146, 11, 'OSMANELİ');
INSERT INTO public."Districts" VALUES (147, 11, 'PAZARYERİ');
INSERT INTO public."Districts" VALUES (148, 11, 'SÖĞÜT');
INSERT INTO public."Districts" VALUES (149, 11, 'YENİPAZAR');
INSERT INTO public."Districts" VALUES (150, 12, 'ADAKLI');
INSERT INTO public."Districts" VALUES (151, 12, 'GENÇ');
INSERT INTO public."Districts" VALUES (152, 12, 'KARLIOVA');
INSERT INTO public."Districts" VALUES (153, 12, 'KİĞI');
INSERT INTO public."Districts" VALUES (154, 12, 'SOLHAN');
INSERT INTO public."Districts" VALUES (155, 12, 'YAYLADERE');
INSERT INTO public."Districts" VALUES (156, 12, 'YEDİSU');
INSERT INTO public."Districts" VALUES (157, 13, 'ADİLCEVAZ');
INSERT INTO public."Districts" VALUES (158, 13, 'AHLAT');
INSERT INTO public."Districts" VALUES (159, 13, 'GÜROYMAK');
INSERT INTO public."Districts" VALUES (160, 13, 'HİZAN');
INSERT INTO public."Districts" VALUES (161, 13, 'MUTKİ');
INSERT INTO public."Districts" VALUES (162, 13, 'TATVAN');
INSERT INTO public."Districts" VALUES (163, 14, 'DÖRTDİVAN');
INSERT INTO public."Districts" VALUES (164, 14, 'GEREDE');
INSERT INTO public."Districts" VALUES (165, 14, 'GÖYNÜK');
INSERT INTO public."Districts" VALUES (166, 14, 'KIBRISCIK');
INSERT INTO public."Districts" VALUES (167, 14, 'MENGEN');
INSERT INTO public."Districts" VALUES (168, 14, 'MUDURNU');
INSERT INTO public."Districts" VALUES (169, 14, 'SEBEN');
INSERT INTO public."Districts" VALUES (170, 14, 'YENİÇAĞA');
INSERT INTO public."Districts" VALUES (171, 15, 'AĞLASUN');
INSERT INTO public."Districts" VALUES (172, 15, 'ALTINYAYLA');
INSERT INTO public."Districts" VALUES (173, 15, 'BUCAK');
INSERT INTO public."Districts" VALUES (174, 15, 'ÇAVDIR');
INSERT INTO public."Districts" VALUES (175, 15, 'ÇELTİKÇİ');
INSERT INTO public."Districts" VALUES (176, 15, 'GÖLHİSAR');
INSERT INTO public."Districts" VALUES (177, 15, 'KARAMANLI');
INSERT INTO public."Districts" VALUES (178, 15, 'KEMER');
INSERT INTO public."Districts" VALUES (179, 15, 'TEFENNİ');
INSERT INTO public."Districts" VALUES (180, 15, 'YEŞİLOVA');
INSERT INTO public."Districts" VALUES (181, 16, 'BÜYÜKORHAN');
INSERT INTO public."Districts" VALUES (182, 16, 'GEMLİK');
INSERT INTO public."Districts" VALUES (183, 16, 'GÜRSU');
INSERT INTO public."Districts" VALUES (184, 16, 'HARMANCIK');
INSERT INTO public."Districts" VALUES (185, 16, 'İNEGÖL');
INSERT INTO public."Districts" VALUES (186, 16, 'İZNİK');
INSERT INTO public."Districts" VALUES (187, 16, 'KARACABEY');
INSERT INTO public."Districts" VALUES (188, 16, 'KELES');
INSERT INTO public."Districts" VALUES (189, 16, 'KESTEL');
INSERT INTO public."Districts" VALUES (190, 16, 'MUDANYA');
INSERT INTO public."Districts" VALUES (191, 16, 'MUSTAFAKEMALPAŞA');
INSERT INTO public."Districts" VALUES (192, 16, 'NİLÜFER');
INSERT INTO public."Districts" VALUES (193, 16, 'ORHANELİ');
INSERT INTO public."Districts" VALUES (194, 16, 'ORHANGAZİ');
INSERT INTO public."Districts" VALUES (195, 16, 'OSMANGAZİ');
INSERT INTO public."Districts" VALUES (196, 16, 'YENİŞEHİR');
INSERT INTO public."Districts" VALUES (197, 16, 'YILDIRIM');
INSERT INTO public."Districts" VALUES (198, 17, 'AYVACIK');
INSERT INTO public."Districts" VALUES (199, 17, 'BAYRAMİÇ');
INSERT INTO public."Districts" VALUES (200, 17, 'BİGA');
INSERT INTO public."Districts" VALUES (201, 17, 'BOZCAADA');
INSERT INTO public."Districts" VALUES (202, 17, 'ÇAN');
INSERT INTO public."Districts" VALUES (203, 17, 'ECEABAT');
INSERT INTO public."Districts" VALUES (204, 17, 'EZİNE');
INSERT INTO public."Districts" VALUES (205, 17, 'GELİBOLU');
INSERT INTO public."Districts" VALUES (206, 17, 'GÖKÇEADA');
INSERT INTO public."Districts" VALUES (207, 17, 'LAPSEKİ');
INSERT INTO public."Districts" VALUES (208, 17, 'YENİCE');
INSERT INTO public."Districts" VALUES (209, 18, 'ATKARACALAR');
INSERT INTO public."Districts" VALUES (210, 18, 'BAYRAMÖREN');
INSERT INTO public."Districts" VALUES (211, 18, 'ÇERKEŞ');
INSERT INTO public."Districts" VALUES (212, 18, 'ELDİVAN');
INSERT INTO public."Districts" VALUES (213, 18, 'ILGAZ');
INSERT INTO public."Districts" VALUES (214, 18, 'KIZILIRMAK');
INSERT INTO public."Districts" VALUES (215, 18, 'KORGUN');
INSERT INTO public."Districts" VALUES (216, 18, 'KURŞUNLU');
INSERT INTO public."Districts" VALUES (217, 18, 'ORTA');
INSERT INTO public."Districts" VALUES (218, 18, 'ŞABANÖZÜ');
INSERT INTO public."Districts" VALUES (219, 18, 'YAPRAKLI');
INSERT INTO public."Districts" VALUES (220, 19, 'ALACA');
INSERT INTO public."Districts" VALUES (221, 19, 'BAYAT');
INSERT INTO public."Districts" VALUES (222, 19, 'BOĞAZKALE');
INSERT INTO public."Districts" VALUES (223, 19, 'DODURGA');
INSERT INTO public."Districts" VALUES (224, 19, 'İSKİLİP');
INSERT INTO public."Districts" VALUES (225, 19, 'KARGI');
INSERT INTO public."Districts" VALUES (226, 19, 'LAÇİN');
INSERT INTO public."Districts" VALUES (227, 19, 'MECİTÖZÜ');
INSERT INTO public."Districts" VALUES (228, 19, 'OĞUZLAR');
INSERT INTO public."Districts" VALUES (229, 19, 'ORTAKÖY');
INSERT INTO public."Districts" VALUES (230, 19, 'OSMANCIK');
INSERT INTO public."Districts" VALUES (231, 19, 'SUNGURLU');
INSERT INTO public."Districts" VALUES (232, 19, 'UĞURLUDAĞ');
INSERT INTO public."Districts" VALUES (233, 20, 'ACIPAYAM');
INSERT INTO public."Districts" VALUES (234, 20, 'BABADAĞ');
INSERT INTO public."Districts" VALUES (235, 20, 'BAKLAN');
INSERT INTO public."Districts" VALUES (236, 20, 'BEKİLLİ');
INSERT INTO public."Districts" VALUES (237, 20, 'BEYAĞAÇ');
INSERT INTO public."Districts" VALUES (238, 20, 'BOZKURT');
INSERT INTO public."Districts" VALUES (239, 20, 'BULDAN');
INSERT INTO public."Districts" VALUES (240, 20, 'ÇAL');
INSERT INTO public."Districts" VALUES (241, 20, 'ÇAMELİ');
INSERT INTO public."Districts" VALUES (242, 20, 'ÇARDAK');
INSERT INTO public."Districts" VALUES (243, 20, 'ÇİVRİL');
INSERT INTO public."Districts" VALUES (244, 20, 'GÜNEY');
INSERT INTO public."Districts" VALUES (245, 20, 'HONAZ');
INSERT INTO public."Districts" VALUES (246, 20, 'KALE');
INSERT INTO public."Districts" VALUES (247, 20, 'MERKEZEFENDİ');
INSERT INTO public."Districts" VALUES (248, 20, 'PAMUKKALE');
INSERT INTO public."Districts" VALUES (249, 20, 'SARAYKÖY');
INSERT INTO public."Districts" VALUES (250, 20, 'SERİNHİSAR');
INSERT INTO public."Districts" VALUES (251, 20, 'TAVAS');
INSERT INTO public."Districts" VALUES (252, 21, 'BAĞLAR');
INSERT INTO public."Districts" VALUES (253, 21, 'BİSMİL');
INSERT INTO public."Districts" VALUES (254, 21, 'ÇERMİK');
INSERT INTO public."Districts" VALUES (255, 21, 'ÇINAR');
INSERT INTO public."Districts" VALUES (256, 21, 'ÇÜNGÜŞ');
INSERT INTO public."Districts" VALUES (257, 21, 'DİCLE');
INSERT INTO public."Districts" VALUES (258, 21, 'EĞİL');
INSERT INTO public."Districts" VALUES (259, 21, 'ERGANİ');
INSERT INTO public."Districts" VALUES (260, 21, 'HANİ');
INSERT INTO public."Districts" VALUES (261, 21, 'HAZRO');
INSERT INTO public."Districts" VALUES (262, 21, 'KAYAPINAR');
INSERT INTO public."Districts" VALUES (263, 21, 'KOCAKÖY');
INSERT INTO public."Districts" VALUES (264, 21, 'KULP');
INSERT INTO public."Districts" VALUES (265, 21, 'LİCE');
INSERT INTO public."Districts" VALUES (266, 21, 'SİLVAN');
INSERT INTO public."Districts" VALUES (267, 21, 'SUR');
INSERT INTO public."Districts" VALUES (268, 21, 'YENİŞEHİR');
INSERT INTO public."Districts" VALUES (269, 22, 'ENEZ');
INSERT INTO public."Districts" VALUES (270, 22, 'HAVSA');
INSERT INTO public."Districts" VALUES (271, 22, 'İPSALA');
INSERT INTO public."Districts" VALUES (272, 22, 'KEŞAN');
INSERT INTO public."Districts" VALUES (273, 22, 'LALAPAŞA');
INSERT INTO public."Districts" VALUES (274, 22, 'MERİÇ');
INSERT INTO public."Districts" VALUES (275, 22, 'SÜLOĞLU');
INSERT INTO public."Districts" VALUES (276, 22, 'UZUNKÖPRÜ');
INSERT INTO public."Districts" VALUES (277, 23, 'AĞIN');
INSERT INTO public."Districts" VALUES (278, 23, 'ALACAKAYA');
INSERT INTO public."Districts" VALUES (279, 23, 'ARICAK');
INSERT INTO public."Districts" VALUES (280, 23, 'BASKİL');
INSERT INTO public."Districts" VALUES (281, 23, 'KARAKOÇAN');
INSERT INTO public."Districts" VALUES (282, 23, 'KEBAN');
INSERT INTO public."Districts" VALUES (283, 23, 'KOVANCILAR');
INSERT INTO public."Districts" VALUES (284, 23, 'MADEN');
INSERT INTO public."Districts" VALUES (285, 23, 'PALU');
INSERT INTO public."Districts" VALUES (286, 23, 'SİVRİCE');
INSERT INTO public."Districts" VALUES (287, 24, 'ÇAYIRLI');
INSERT INTO public."Districts" VALUES (288, 24, 'İLİÇ');
INSERT INTO public."Districts" VALUES (289, 24, 'KEMAH');
INSERT INTO public."Districts" VALUES (290, 24, 'KEMALİYE');
INSERT INTO public."Districts" VALUES (291, 24, 'OTLUKBELİ');
INSERT INTO public."Districts" VALUES (292, 24, 'REFAHİYE');
INSERT INTO public."Districts" VALUES (293, 24, 'TERCAN');
INSERT INTO public."Districts" VALUES (294, 24, 'ÜZÜMLÜ');
INSERT INTO public."Districts" VALUES (295, 25, 'AŞKALE');
INSERT INTO public."Districts" VALUES (296, 25, 'AZİZİYE');
INSERT INTO public."Districts" VALUES (297, 25, 'ÇAT');
INSERT INTO public."Districts" VALUES (298, 25, 'HINIS');
INSERT INTO public."Districts" VALUES (299, 25, 'HORASAN');
INSERT INTO public."Districts" VALUES (300, 25, 'İSPİR');
INSERT INTO public."Districts" VALUES (301, 25, 'KARAÇOBAN');
INSERT INTO public."Districts" VALUES (302, 25, 'KARAYAZI');
INSERT INTO public."Districts" VALUES (303, 25, 'KÖPRÜKÖY');
INSERT INTO public."Districts" VALUES (304, 25, 'NARMAN');
INSERT INTO public."Districts" VALUES (305, 25, 'OLTU');
INSERT INTO public."Districts" VALUES (306, 25, 'OLUR');
INSERT INTO public."Districts" VALUES (307, 25, 'PALANDÖKEN');
INSERT INTO public."Districts" VALUES (308, 25, 'PASİNLER');
INSERT INTO public."Districts" VALUES (309, 25, 'PAZARYOLU');
INSERT INTO public."Districts" VALUES (310, 25, 'ŞENKAYA');
INSERT INTO public."Districts" VALUES (311, 25, 'TEKMAN');
INSERT INTO public."Districts" VALUES (312, 25, 'TORTUM');
INSERT INTO public."Districts" VALUES (313, 25, 'UZUNDERE');
INSERT INTO public."Districts" VALUES (314, 25, 'YAKUTİYE');
INSERT INTO public."Districts" VALUES (315, 26, 'ALPU');
INSERT INTO public."Districts" VALUES (316, 26, 'BEYLİKOVA');
INSERT INTO public."Districts" VALUES (317, 26, 'ÇİFTELER');
INSERT INTO public."Districts" VALUES (318, 26, 'GÜNYÜZÜ');
INSERT INTO public."Districts" VALUES (319, 26, 'HAN');
INSERT INTO public."Districts" VALUES (320, 26, 'İNÖNÜ');
INSERT INTO public."Districts" VALUES (321, 26, 'MAHMUDİYE');
INSERT INTO public."Districts" VALUES (322, 26, 'MİHALGAZİ');
INSERT INTO public."Districts" VALUES (323, 26, 'MİHALIÇÇIK');
INSERT INTO public."Districts" VALUES (324, 26, 'ODUNPAZARI');
INSERT INTO public."Districts" VALUES (325, 26, 'SARICAKAYA');
INSERT INTO public."Districts" VALUES (326, 26, 'SEYİTGAZİ');
INSERT INTO public."Districts" VALUES (327, 26, 'SİVRİHİSAR');
INSERT INTO public."Districts" VALUES (328, 26, 'TEPEBAŞI');
INSERT INTO public."Districts" VALUES (329, 27, 'ARABAN');
INSERT INTO public."Districts" VALUES (330, 27, 'İSLAHİYE');
INSERT INTO public."Districts" VALUES (331, 27, 'KARKAMIŞ');
INSERT INTO public."Districts" VALUES (332, 27, 'NİZİP');
INSERT INTO public."Districts" VALUES (333, 27, 'NURDAĞI');
INSERT INTO public."Districts" VALUES (334, 27, 'OĞUZELİ');
INSERT INTO public."Districts" VALUES (335, 27, 'ŞAHİNBEY');
INSERT INTO public."Districts" VALUES (336, 27, 'ŞEHİTKAMİL');
INSERT INTO public."Districts" VALUES (337, 27, 'YAVUZELİ');
INSERT INTO public."Districts" VALUES (338, 28, 'ALUCRA');
INSERT INTO public."Districts" VALUES (339, 28, 'BULANCAK');
INSERT INTO public."Districts" VALUES (340, 28, 'ÇAMOLUK');
INSERT INTO public."Districts" VALUES (341, 28, 'ÇANAKÇI');
INSERT INTO public."Districts" VALUES (342, 28, 'DERELİ');
INSERT INTO public."Districts" VALUES (343, 28, 'DOĞANKENT');
INSERT INTO public."Districts" VALUES (344, 28, 'ESPİYE');
INSERT INTO public."Districts" VALUES (345, 28, 'EYNESİL');
INSERT INTO public."Districts" VALUES (346, 28, 'GÖRELE');
INSERT INTO public."Districts" VALUES (347, 28, 'GÜCE');
INSERT INTO public."Districts" VALUES (348, 28, 'KEŞAP');
INSERT INTO public."Districts" VALUES (349, 28, 'PİRAZİZ');
INSERT INTO public."Districts" VALUES (350, 28, 'ŞEBİNKARAHİSAR');
INSERT INTO public."Districts" VALUES (351, 28, 'TİREBOLU');
INSERT INTO public."Districts" VALUES (352, 28, 'YAĞLIDERE');
INSERT INTO public."Districts" VALUES (353, 29, 'KELKİT');
INSERT INTO public."Districts" VALUES (354, 29, 'KÖSE');
INSERT INTO public."Districts" VALUES (355, 29, 'KÜRTÜN');
INSERT INTO public."Districts" VALUES (356, 29, 'ŞİRAN');
INSERT INTO public."Districts" VALUES (357, 29, 'TORUL');
INSERT INTO public."Districts" VALUES (358, 30, 'ÇUKURCA');
INSERT INTO public."Districts" VALUES (359, 30, 'DERECİK');
INSERT INTO public."Districts" VALUES (360, 30, 'ŞEMDİNLİ');
INSERT INTO public."Districts" VALUES (361, 30, 'YÜKSEKOVA');
INSERT INTO public."Districts" VALUES (362, 31, 'ALTINÖZÜ');
INSERT INTO public."Districts" VALUES (363, 31, 'ANTAKYA');
INSERT INTO public."Districts" VALUES (364, 31, 'ARSUZ');
INSERT INTO public."Districts" VALUES (365, 31, 'BELEN');
INSERT INTO public."Districts" VALUES (366, 31, 'DEFNE');
INSERT INTO public."Districts" VALUES (367, 31, 'DÖRTYOL');
INSERT INTO public."Districts" VALUES (368, 31, 'ERZİN');
INSERT INTO public."Districts" VALUES (369, 31, 'HASSA');
INSERT INTO public."Districts" VALUES (370, 31, 'İSKENDERUN');
INSERT INTO public."Districts" VALUES (371, 31, 'KIRIKHAN');
INSERT INTO public."Districts" VALUES (372, 31, 'KUMLU');
INSERT INTO public."Districts" VALUES (373, 31, 'PAYAS');
INSERT INTO public."Districts" VALUES (374, 31, 'REYHANLI');
INSERT INTO public."Districts" VALUES (375, 31, 'SAMANDAĞ');
INSERT INTO public."Districts" VALUES (376, 31, 'YAYLADAĞI');
INSERT INTO public."Districts" VALUES (377, 32, 'AKSU');
INSERT INTO public."Districts" VALUES (378, 32, 'ATABEY');
INSERT INTO public."Districts" VALUES (379, 32, 'EĞİRDİR');
INSERT INTO public."Districts" VALUES (380, 32, 'GELENDOST');
INSERT INTO public."Districts" VALUES (381, 32, 'GÖNEN');
INSERT INTO public."Districts" VALUES (382, 32, 'KEÇİBORLU');
INSERT INTO public."Districts" VALUES (383, 32, 'ŞARKİKARAAĞAÇ');
INSERT INTO public."Districts" VALUES (384, 32, 'SENİRKENT');
INSERT INTO public."Districts" VALUES (385, 32, 'SÜTÇÜLER');
INSERT INTO public."Districts" VALUES (386, 32, 'ULUBORLU');
INSERT INTO public."Districts" VALUES (387, 32, 'YALVAÇ');
INSERT INTO public."Districts" VALUES (388, 32, 'YENİŞARBADEMLİ');
INSERT INTO public."Districts" VALUES (389, 33, 'AKDENİZ');
INSERT INTO public."Districts" VALUES (390, 33, 'ANAMUR');
INSERT INTO public."Districts" VALUES (391, 33, 'AYDINCIK');
INSERT INTO public."Districts" VALUES (392, 33, 'BOZYAZI');
INSERT INTO public."Districts" VALUES (393, 33, 'ÇAMLIYAYLA');
INSERT INTO public."Districts" VALUES (394, 33, 'ERDEMLİ');
INSERT INTO public."Districts" VALUES (395, 33, 'GÜLNAR');
INSERT INTO public."Districts" VALUES (396, 33, 'MEZİTLİ');
INSERT INTO public."Districts" VALUES (397, 33, 'MUT');
INSERT INTO public."Districts" VALUES (398, 33, 'SİLİFKE');
INSERT INTO public."Districts" VALUES (399, 33, 'TARSUS');
INSERT INTO public."Districts" VALUES (400, 33, 'TOROSLAR');
INSERT INTO public."Districts" VALUES (401, 33, 'YENİŞEHİR');
INSERT INTO public."Districts" VALUES (402, 34, 'ADALAR');
INSERT INTO public."Districts" VALUES (403, 34, 'ARNAVUTKÖY');
INSERT INTO public."Districts" VALUES (404, 34, 'ATAŞEHİR');
INSERT INTO public."Districts" VALUES (405, 34, 'AVCILAR');
INSERT INTO public."Districts" VALUES (406, 34, 'BAĞCILAR');
INSERT INTO public."Districts" VALUES (407, 34, 'BAHÇELİEVLER');
INSERT INTO public."Districts" VALUES (408, 34, 'BAKIRKÖY');
INSERT INTO public."Districts" VALUES (409, 34, 'BAŞAKŞEHİR');
INSERT INTO public."Districts" VALUES (410, 34, 'BAYRAMPAŞA');
INSERT INTO public."Districts" VALUES (411, 34, 'BEŞİKTAŞ');
INSERT INTO public."Districts" VALUES (412, 34, 'BEYKOZ');
INSERT INTO public."Districts" VALUES (413, 34, 'BEYLİKDÜZÜ');
INSERT INTO public."Districts" VALUES (414, 34, 'BEYOĞLU');
INSERT INTO public."Districts" VALUES (415, 34, 'BÜYÜKÇEKMECE');
INSERT INTO public."Districts" VALUES (416, 34, 'ÇATALCA');
INSERT INTO public."Districts" VALUES (417, 34, 'ÇEKMEKÖY');
INSERT INTO public."Districts" VALUES (418, 34, 'ESENLER');
INSERT INTO public."Districts" VALUES (419, 34, 'ESENYURT');
INSERT INTO public."Districts" VALUES (420, 34, 'EYÜPSULTAN');
INSERT INTO public."Districts" VALUES (421, 34, 'FATİH');
INSERT INTO public."Districts" VALUES (422, 34, 'GAZİOSMANPAŞA');
INSERT INTO public."Districts" VALUES (423, 34, 'GÜNGÖREN');
INSERT INTO public."Districts" VALUES (424, 34, 'KADIKÖY');
INSERT INTO public."Districts" VALUES (425, 34, 'KAĞITHANE');
INSERT INTO public."Districts" VALUES (426, 34, 'KARTAL');
INSERT INTO public."Districts" VALUES (427, 34, 'KÜÇÜKÇEKMECE');
INSERT INTO public."Districts" VALUES (428, 34, 'MALTEPE');
INSERT INTO public."Districts" VALUES (429, 34, 'PENDİK');
INSERT INTO public."Districts" VALUES (430, 34, 'SANCAKTEPE');
INSERT INTO public."Districts" VALUES (431, 34, 'SARIYER');
INSERT INTO public."Districts" VALUES (432, 34, 'ŞİLE');
INSERT INTO public."Districts" VALUES (433, 34, 'SİLİVRİ');
INSERT INTO public."Districts" VALUES (434, 34, 'ŞİŞLİ');
INSERT INTO public."Districts" VALUES (435, 34, 'SULTANBEYLİ');
INSERT INTO public."Districts" VALUES (436, 34, 'SULTANGAZİ');
INSERT INTO public."Districts" VALUES (437, 34, 'TUZLA');
INSERT INTO public."Districts" VALUES (438, 34, 'ÜMRANİYE');
INSERT INTO public."Districts" VALUES (439, 34, 'ÜSKÜDAR');
INSERT INTO public."Districts" VALUES (440, 34, 'ZEYTİNBURNU');
INSERT INTO public."Districts" VALUES (441, 35, 'ALİAĞA');
INSERT INTO public."Districts" VALUES (442, 35, 'BALÇOVA');
INSERT INTO public."Districts" VALUES (443, 35, 'BAYINDIR');
INSERT INTO public."Districts" VALUES (444, 35, 'BAYRAKLI');
INSERT INTO public."Districts" VALUES (445, 35, 'BERGAMA');
INSERT INTO public."Districts" VALUES (446, 35, 'BEYDAĞ');
INSERT INTO public."Districts" VALUES (447, 35, 'BORNOVA');
INSERT INTO public."Districts" VALUES (448, 35, 'BUCA');
INSERT INTO public."Districts" VALUES (449, 35, 'ÇEŞME');
INSERT INTO public."Districts" VALUES (450, 35, 'ÇİĞLİ');
INSERT INTO public."Districts" VALUES (451, 35, 'DİKİLİ');
INSERT INTO public."Districts" VALUES (452, 35, 'FOÇA');
INSERT INTO public."Districts" VALUES (453, 35, 'GAZİEMİR');
INSERT INTO public."Districts" VALUES (454, 35, 'GÜZELBAHÇE');
INSERT INTO public."Districts" VALUES (455, 35, 'KARABAĞLAR');
INSERT INTO public."Districts" VALUES (456, 35, 'KARABURUN');
INSERT INTO public."Districts" VALUES (457, 35, 'KARŞIYAKA');
INSERT INTO public."Districts" VALUES (458, 35, 'KEMALPAŞA');
INSERT INTO public."Districts" VALUES (459, 35, 'KINIK');
INSERT INTO public."Districts" VALUES (460, 35, 'KİRAZ');
INSERT INTO public."Districts" VALUES (461, 35, 'KONAK');
INSERT INTO public."Districts" VALUES (462, 35, 'MENDERES');
INSERT INTO public."Districts" VALUES (463, 35, 'MENEMEN');
INSERT INTO public."Districts" VALUES (464, 35, 'NARLIDERE');
INSERT INTO public."Districts" VALUES (465, 35, 'ÖDEMİŞ');
INSERT INTO public."Districts" VALUES (466, 35, 'SEFERİHİSAR');
INSERT INTO public."Districts" VALUES (467, 35, 'SELÇUK');
INSERT INTO public."Districts" VALUES (468, 35, 'TİRE');
INSERT INTO public."Districts" VALUES (469, 35, 'TORBALI');
INSERT INTO public."Districts" VALUES (470, 35, 'URLA');
INSERT INTO public."Districts" VALUES (471, 36, 'AKYAKA');
INSERT INTO public."Districts" VALUES (472, 36, 'ARPAÇAY');
INSERT INTO public."Districts" VALUES (473, 36, 'DİGOR');
INSERT INTO public."Districts" VALUES (474, 36, 'KAĞIZMAN');
INSERT INTO public."Districts" VALUES (475, 36, 'SARIKAMIŞ');
INSERT INTO public."Districts" VALUES (476, 36, 'SELİM');
INSERT INTO public."Districts" VALUES (477, 36, 'SUSUZ');
INSERT INTO public."Districts" VALUES (478, 37, 'ABANA');
INSERT INTO public."Districts" VALUES (479, 37, 'AĞLI');
INSERT INTO public."Districts" VALUES (480, 37, 'ARAÇ');
INSERT INTO public."Districts" VALUES (481, 37, 'AZDAVAY');
INSERT INTO public."Districts" VALUES (482, 37, 'BOZKURT');
INSERT INTO public."Districts" VALUES (483, 37, 'ÇATALZEYTİN');
INSERT INTO public."Districts" VALUES (484, 37, 'CİDE');
INSERT INTO public."Districts" VALUES (485, 37, 'DADAY');
INSERT INTO public."Districts" VALUES (486, 37, 'DEVREKANİ');
INSERT INTO public."Districts" VALUES (487, 37, 'DOĞANYURT');
INSERT INTO public."Districts" VALUES (488, 37, 'HANÖNÜ');
INSERT INTO public."Districts" VALUES (489, 37, 'İHSANGAZİ');
INSERT INTO public."Districts" VALUES (490, 37, 'İNEBOLU');
INSERT INTO public."Districts" VALUES (491, 37, 'KÜRE');
INSERT INTO public."Districts" VALUES (492, 37, 'PINARBAŞI');
INSERT INTO public."Districts" VALUES (493, 37, 'ŞENPAZAR');
INSERT INTO public."Districts" VALUES (494, 37, 'SEYDİLER');
INSERT INTO public."Districts" VALUES (495, 37, 'TAŞKÖPRÜ');
INSERT INTO public."Districts" VALUES (496, 37, 'TOSYA');
INSERT INTO public."Districts" VALUES (497, 38, 'AKKIŞLA');
INSERT INTO public."Districts" VALUES (498, 38, 'BÜNYAN');
INSERT INTO public."Districts" VALUES (499, 38, 'DEVELİ');
INSERT INTO public."Districts" VALUES (500, 38, 'FELAHİYE');
INSERT INTO public."Districts" VALUES (501, 38, 'HACILAR');
INSERT INTO public."Districts" VALUES (502, 38, 'İNCESU');
INSERT INTO public."Districts" VALUES (503, 38, 'KOCASİNAN');
INSERT INTO public."Districts" VALUES (504, 38, 'MELİKGAZİ');
INSERT INTO public."Districts" VALUES (505, 38, 'ÖZVATAN');
INSERT INTO public."Districts" VALUES (506, 38, 'PINARBAŞI');
INSERT INTO public."Districts" VALUES (507, 38, 'SARIOĞLAN');
INSERT INTO public."Districts" VALUES (508, 38, 'SARIZ');
INSERT INTO public."Districts" VALUES (509, 38, 'TALAS');
INSERT INTO public."Districts" VALUES (510, 38, 'TOMARZA');
INSERT INTO public."Districts" VALUES (511, 38, 'YAHYALI');
INSERT INTO public."Districts" VALUES (512, 38, 'YEŞİLHİSAR');
INSERT INTO public."Districts" VALUES (513, 39, 'BABAESKİ');
INSERT INTO public."Districts" VALUES (514, 39, 'DEMİRKÖY');
INSERT INTO public."Districts" VALUES (515, 39, 'KOFÇAZ');
INSERT INTO public."Districts" VALUES (516, 39, 'LÜLEBURGAZ');
INSERT INTO public."Districts" VALUES (517, 39, 'PEHLİVANKÖY');
INSERT INTO public."Districts" VALUES (518, 39, 'PINARHİSAR');
INSERT INTO public."Districts" VALUES (519, 39, 'VİZE');
INSERT INTO public."Districts" VALUES (520, 40, 'AKÇAKENT');
INSERT INTO public."Districts" VALUES (521, 40, 'AKPINAR');
INSERT INTO public."Districts" VALUES (522, 40, 'BOZTEPE');
INSERT INTO public."Districts" VALUES (523, 40, 'ÇİÇEKDAĞI');
INSERT INTO public."Districts" VALUES (524, 40, 'KAMAN');
INSERT INTO public."Districts" VALUES (525, 40, 'MUCUR');
INSERT INTO public."Districts" VALUES (526, 41, 'BAŞİSKELE');
INSERT INTO public."Districts" VALUES (527, 41, 'ÇAYIROVA');
INSERT INTO public."Districts" VALUES (528, 41, 'DARICA');
INSERT INTO public."Districts" VALUES (529, 41, 'DERİNCE');
INSERT INTO public."Districts" VALUES (530, 41, 'DİLOVASI');
INSERT INTO public."Districts" VALUES (531, 41, 'GEBZE');
INSERT INTO public."Districts" VALUES (532, 41, 'GÖLCÜK');
INSERT INTO public."Districts" VALUES (533, 41, 'İZMİT');
INSERT INTO public."Districts" VALUES (534, 41, 'KANDIRA');
INSERT INTO public."Districts" VALUES (535, 41, 'KARAMÜRSEL');
INSERT INTO public."Districts" VALUES (536, 41, 'KARTEPE');
INSERT INTO public."Districts" VALUES (537, 41, 'KÖRFEZ');
INSERT INTO public."Districts" VALUES (538, 42, 'AHIRLI');
INSERT INTO public."Districts" VALUES (539, 42, 'AKÖREN');
INSERT INTO public."Districts" VALUES (540, 42, 'AKŞEHİR');
INSERT INTO public."Districts" VALUES (541, 42, 'ALTINEKİN');
INSERT INTO public."Districts" VALUES (542, 42, 'BEYŞEHİR');
INSERT INTO public."Districts" VALUES (543, 42, 'BOZKIR');
INSERT INTO public."Districts" VALUES (544, 42, 'ÇELTİK');
INSERT INTO public."Districts" VALUES (545, 42, 'CİHANBEYLİ');
INSERT INTO public."Districts" VALUES (546, 42, 'ÇUMRA');
INSERT INTO public."Districts" VALUES (547, 42, 'DERBENT');
INSERT INTO public."Districts" VALUES (548, 42, 'DEREBUCAK');
INSERT INTO public."Districts" VALUES (549, 42, 'DOĞANHİSAR');
INSERT INTO public."Districts" VALUES (550, 42, 'EMİRGAZİ');
INSERT INTO public."Districts" VALUES (551, 42, 'EREĞLİ');
INSERT INTO public."Districts" VALUES (552, 42, 'GÜNEYSINIR');
INSERT INTO public."Districts" VALUES (553, 42, 'HADİM');
INSERT INTO public."Districts" VALUES (554, 42, 'HALKAPINAR');
INSERT INTO public."Districts" VALUES (555, 42, 'HÜYÜK');
INSERT INTO public."Districts" VALUES (556, 42, 'ILGIN');
INSERT INTO public."Districts" VALUES (557, 42, 'KADINHANI');
INSERT INTO public."Districts" VALUES (558, 42, 'KARAPINAR');
INSERT INTO public."Districts" VALUES (559, 42, 'KARATAY');
INSERT INTO public."Districts" VALUES (560, 42, 'KULU');
INSERT INTO public."Districts" VALUES (561, 42, 'MERAM');
INSERT INTO public."Districts" VALUES (562, 42, 'SARAYÖNÜ');
INSERT INTO public."Districts" VALUES (563, 42, 'SELÇUKLU');
INSERT INTO public."Districts" VALUES (564, 42, 'SEYDİŞEHİR');
INSERT INTO public."Districts" VALUES (565, 42, 'TAŞKENT');
INSERT INTO public."Districts" VALUES (566, 42, 'TUZLUKÇU');
INSERT INTO public."Districts" VALUES (567, 42, 'YALIHÜYÜK');
INSERT INTO public."Districts" VALUES (568, 42, 'YUNAK');
INSERT INTO public."Districts" VALUES (569, 43, 'ALTINTAŞ');
INSERT INTO public."Districts" VALUES (570, 43, 'ASLANAPA');
INSERT INTO public."Districts" VALUES (571, 43, 'ÇAVDARHİSAR');
INSERT INTO public."Districts" VALUES (572, 43, 'DOMANİÇ');
INSERT INTO public."Districts" VALUES (573, 43, 'DUMLUPINAR');
INSERT INTO public."Districts" VALUES (574, 43, 'EMET');
INSERT INTO public."Districts" VALUES (575, 43, 'GEDİZ');
INSERT INTO public."Districts" VALUES (576, 43, 'HİSARCIK');
INSERT INTO public."Districts" VALUES (577, 43, 'PAZARLAR');
INSERT INTO public."Districts" VALUES (578, 43, 'ŞAPHANE');
INSERT INTO public."Districts" VALUES (579, 43, 'SİMAV');
INSERT INTO public."Districts" VALUES (580, 43, 'TAVŞANLI');
INSERT INTO public."Districts" VALUES (581, 44, 'AKÇADAĞ');
INSERT INTO public."Districts" VALUES (582, 44, 'ARAPGİR');
INSERT INTO public."Districts" VALUES (583, 44, 'ARGUVAN');
INSERT INTO public."Districts" VALUES (584, 44, 'BATTALGAZİ');
INSERT INTO public."Districts" VALUES (585, 44, 'DARENDE');
INSERT INTO public."Districts" VALUES (586, 44, 'DOĞANŞEHİR');
INSERT INTO public."Districts" VALUES (587, 44, 'DOĞANYOL');
INSERT INTO public."Districts" VALUES (588, 44, 'HEKİMHAN');
INSERT INTO public."Districts" VALUES (589, 44, 'KALE');
INSERT INTO public."Districts" VALUES (590, 44, 'KULUNCAK');
INSERT INTO public."Districts" VALUES (591, 44, 'PÜTÜRGE');
INSERT INTO public."Districts" VALUES (592, 44, 'YAZIHAN');
INSERT INTO public."Districts" VALUES (593, 44, 'YEŞİLYURT');
INSERT INTO public."Districts" VALUES (594, 45, 'AHMETLİ');
INSERT INTO public."Districts" VALUES (595, 45, 'AKHİSAR');
INSERT INTO public."Districts" VALUES (596, 45, 'ALAŞEHİR');
INSERT INTO public."Districts" VALUES (597, 45, 'DEMİRCİ');
INSERT INTO public."Districts" VALUES (598, 45, 'GÖLMARMARA');
INSERT INTO public."Districts" VALUES (599, 45, 'GÖRDES');
INSERT INTO public."Districts" VALUES (600, 45, 'KIRKAĞAÇ');
INSERT INTO public."Districts" VALUES (601, 45, 'KÖPRÜBAŞI');
INSERT INTO public."Districts" VALUES (602, 45, 'KULA');
INSERT INTO public."Districts" VALUES (603, 45, 'SALİHLİ');
INSERT INTO public."Districts" VALUES (604, 45, 'SARIGÖL');
INSERT INTO public."Districts" VALUES (605, 45, 'SARUHANLI');
INSERT INTO public."Districts" VALUES (606, 45, 'ŞEHZADELER');
INSERT INTO public."Districts" VALUES (607, 45, 'SELENDİ');
INSERT INTO public."Districts" VALUES (608, 45, 'SOMA');
INSERT INTO public."Districts" VALUES (609, 45, 'TURGUTLU');
INSERT INTO public."Districts" VALUES (610, 45, 'YUNUSEMRE');
INSERT INTO public."Districts" VALUES (611, 46, 'AFŞİN');
INSERT INTO public."Districts" VALUES (612, 46, 'ANDIRIN');
INSERT INTO public."Districts" VALUES (613, 46, 'ÇAĞLAYANCERİT');
INSERT INTO public."Districts" VALUES (614, 46, 'DULKADİROĞLU');
INSERT INTO public."Districts" VALUES (615, 46, 'EKİNÖZÜ');
INSERT INTO public."Districts" VALUES (616, 46, 'ELBİSTAN');
INSERT INTO public."Districts" VALUES (617, 46, 'GÖKSUN');
INSERT INTO public."Districts" VALUES (618, 46, 'NURHAK');
INSERT INTO public."Districts" VALUES (619, 46, 'ONİKİŞUBAT');
INSERT INTO public."Districts" VALUES (620, 46, 'PAZARCIK');
INSERT INTO public."Districts" VALUES (621, 46, 'TÜRKOĞLU');
INSERT INTO public."Districts" VALUES (622, 47, 'ARTUKLU');
INSERT INTO public."Districts" VALUES (623, 47, 'DARGEÇİT');
INSERT INTO public."Districts" VALUES (624, 47, 'DERİK');
INSERT INTO public."Districts" VALUES (625, 47, 'KIZILTEPE');
INSERT INTO public."Districts" VALUES (626, 47, 'MAZIDAĞI');
INSERT INTO public."Districts" VALUES (627, 47, 'MİDYAT');
INSERT INTO public."Districts" VALUES (628, 47, 'NUSAYBİN');
INSERT INTO public."Districts" VALUES (629, 47, 'ÖMERLİ');
INSERT INTO public."Districts" VALUES (630, 47, 'SAVUR');
INSERT INTO public."Districts" VALUES (631, 47, 'YEŞİLLİ');
INSERT INTO public."Districts" VALUES (632, 48, 'BODRUM');
INSERT INTO public."Districts" VALUES (633, 48, 'DALAMAN');
INSERT INTO public."Districts" VALUES (634, 48, 'DATÇA');
INSERT INTO public."Districts" VALUES (635, 48, 'FETHİYE');
INSERT INTO public."Districts" VALUES (636, 48, 'KAVAKLIDERE');
INSERT INTO public."Districts" VALUES (637, 48, 'KÖYCEĞİZ');
INSERT INTO public."Districts" VALUES (638, 48, 'MARMARİS');
INSERT INTO public."Districts" VALUES (639, 48, 'MENTEŞE');
INSERT INTO public."Districts" VALUES (640, 48, 'MİLAS');
INSERT INTO public."Districts" VALUES (641, 48, 'ORTACA');
INSERT INTO public."Districts" VALUES (642, 48, 'SEYDİKEMER');
INSERT INTO public."Districts" VALUES (643, 48, 'ULA');
INSERT INTO public."Districts" VALUES (644, 48, 'YATAĞAN');
INSERT INTO public."Districts" VALUES (645, 49, 'BULANIK');
INSERT INTO public."Districts" VALUES (646, 49, 'HASKÖY');
INSERT INTO public."Districts" VALUES (647, 49, 'KORKUT');
INSERT INTO public."Districts" VALUES (648, 49, 'MALAZGİRT');
INSERT INTO public."Districts" VALUES (649, 49, 'VARTO');
INSERT INTO public."Districts" VALUES (650, 50, 'ACIGÖL');
INSERT INTO public."Districts" VALUES (651, 50, 'AVANOS');
INSERT INTO public."Districts" VALUES (652, 50, 'DERİNKUYU');
INSERT INTO public."Districts" VALUES (653, 50, 'GÜLŞEHİR');
INSERT INTO public."Districts" VALUES (654, 50, 'HACIBEKTAŞ');
INSERT INTO public."Districts" VALUES (655, 50, 'KOZAKLI');
INSERT INTO public."Districts" VALUES (656, 50, 'ÜRGÜP');
INSERT INTO public."Districts" VALUES (657, 51, 'ALTUNHİSAR');
INSERT INTO public."Districts" VALUES (658, 51, 'BOR');
INSERT INTO public."Districts" VALUES (659, 51, 'ÇAMARDI');
INSERT INTO public."Districts" VALUES (660, 51, 'ÇİFTLİK');
INSERT INTO public."Districts" VALUES (661, 51, 'ULUKIŞLA');
INSERT INTO public."Districts" VALUES (662, 52, 'AKKUŞ');
INSERT INTO public."Districts" VALUES (663, 52, 'ALTINORDU');
INSERT INTO public."Districts" VALUES (664, 52, 'AYBASTI');
INSERT INTO public."Districts" VALUES (665, 52, 'ÇAMAŞ');
INSERT INTO public."Districts" VALUES (666, 52, 'ÇATALPINAR');
INSERT INTO public."Districts" VALUES (667, 52, 'ÇAYBAŞI');
INSERT INTO public."Districts" VALUES (668, 52, 'FATSA');
INSERT INTO public."Districts" VALUES (669, 52, 'GÖLKÖY');
INSERT INTO public."Districts" VALUES (670, 52, 'GÜLYALI');
INSERT INTO public."Districts" VALUES (671, 52, 'GÜRGENTEPE');
INSERT INTO public."Districts" VALUES (672, 52, 'İKİZCE');
INSERT INTO public."Districts" VALUES (673, 52, 'KABADÜZ');
INSERT INTO public."Districts" VALUES (674, 52, 'KABATAŞ');
INSERT INTO public."Districts" VALUES (675, 52, 'KORGAN');
INSERT INTO public."Districts" VALUES (676, 52, 'KUMRU');
INSERT INTO public."Districts" VALUES (677, 52, 'MESUDİYE');
INSERT INTO public."Districts" VALUES (678, 52, 'PERŞEMBE');
INSERT INTO public."Districts" VALUES (679, 52, 'ULUBEY');
INSERT INTO public."Districts" VALUES (680, 52, 'ÜNYE');
INSERT INTO public."Districts" VALUES (681, 53, 'ARDEŞEN');
INSERT INTO public."Districts" VALUES (682, 53, 'ÇAMLIHEMŞİN');
INSERT INTO public."Districts" VALUES (683, 53, 'ÇAYELİ');
INSERT INTO public."Districts" VALUES (684, 53, 'DEREPAZARI');
INSERT INTO public."Districts" VALUES (685, 53, 'FINDIKLI');
INSERT INTO public."Districts" VALUES (686, 53, 'GÜNEYSU');
INSERT INTO public."Districts" VALUES (687, 53, 'HEMŞİN');
INSERT INTO public."Districts" VALUES (688, 53, 'İKİZDERE');
INSERT INTO public."Districts" VALUES (689, 53, 'İYİDERE');
INSERT INTO public."Districts" VALUES (690, 53, 'KALKANDERE');
INSERT INTO public."Districts" VALUES (691, 53, 'PAZAR');
INSERT INTO public."Districts" VALUES (692, 54, 'ADAPAZARI');
INSERT INTO public."Districts" VALUES (693, 54, 'AKYAZI');
INSERT INTO public."Districts" VALUES (694, 54, 'ARİFİYE');
INSERT INTO public."Districts" VALUES (695, 54, 'ERENLER');
INSERT INTO public."Districts" VALUES (696, 54, 'FERİZLİ');
INSERT INTO public."Districts" VALUES (697, 54, 'GEYVE');
INSERT INTO public."Districts" VALUES (698, 54, 'HENDEK');
INSERT INTO public."Districts" VALUES (699, 54, 'KARAPÜRÇEK');
INSERT INTO public."Districts" VALUES (700, 54, 'KARASU');
INSERT INTO public."Districts" VALUES (701, 54, 'KAYNARCA');
INSERT INTO public."Districts" VALUES (702, 54, 'KOCAALİ');
INSERT INTO public."Districts" VALUES (703, 54, 'PAMUKOVA');
INSERT INTO public."Districts" VALUES (704, 54, 'SAPANCA');
INSERT INTO public."Districts" VALUES (705, 54, 'SERDİVAN');
INSERT INTO public."Districts" VALUES (706, 54, 'SÖĞÜTLÜ');
INSERT INTO public."Districts" VALUES (707, 54, 'TARAKLI');
INSERT INTO public."Districts" VALUES (708, 55, '19 MAYIS');
INSERT INTO public."Districts" VALUES (709, 55, 'ALAÇAM');
INSERT INTO public."Districts" VALUES (710, 55, 'ASARCIK');
INSERT INTO public."Districts" VALUES (711, 55, 'ATAKUM');
INSERT INTO public."Districts" VALUES (712, 55, 'AYVACIK');
INSERT INTO public."Districts" VALUES (713, 55, 'BAFRA');
INSERT INTO public."Districts" VALUES (714, 55, 'CANİK');
INSERT INTO public."Districts" VALUES (715, 55, 'ÇARŞAMBA');
INSERT INTO public."Districts" VALUES (716, 55, 'HAVZA');
INSERT INTO public."Districts" VALUES (717, 55, 'İLKADIM');
INSERT INTO public."Districts" VALUES (718, 55, 'KAVAK');
INSERT INTO public."Districts" VALUES (719, 55, 'LADİK');
INSERT INTO public."Districts" VALUES (720, 55, 'SALIPAZARI');
INSERT INTO public."Districts" VALUES (721, 55, 'TEKKEKÖY');
INSERT INTO public."Districts" VALUES (722, 55, 'TERME');
INSERT INTO public."Districts" VALUES (723, 55, 'VEZİRKÖPRÜ');
INSERT INTO public."Districts" VALUES (724, 55, 'YAKAKENT');
INSERT INTO public."Districts" VALUES (725, 56, 'BAYKAN');
INSERT INTO public."Districts" VALUES (726, 56, 'ERUH');
INSERT INTO public."Districts" VALUES (727, 56, 'KURTALAN');
INSERT INTO public."Districts" VALUES (728, 56, 'PERVARİ');
INSERT INTO public."Districts" VALUES (729, 56, 'ŞİRVAN');
INSERT INTO public."Districts" VALUES (730, 56, 'TİLLO');
INSERT INTO public."Districts" VALUES (731, 57, 'AYANCIK');
INSERT INTO public."Districts" VALUES (732, 57, 'BOYABAT');
INSERT INTO public."Districts" VALUES (733, 57, 'DİKMEN');
INSERT INTO public."Districts" VALUES (734, 57, 'DURAĞAN');
INSERT INTO public."Districts" VALUES (735, 57, 'ERFELEK');
INSERT INTO public."Districts" VALUES (736, 57, 'GERZE');
INSERT INTO public."Districts" VALUES (737, 57, 'SARAYDÜZÜ');
INSERT INTO public."Districts" VALUES (738, 57, 'TÜRKELİ');
INSERT INTO public."Districts" VALUES (739, 58, 'AKINCILAR');
INSERT INTO public."Districts" VALUES (740, 58, 'ALTINYAYLA');
INSERT INTO public."Districts" VALUES (741, 58, 'DİVRİĞİ');
INSERT INTO public."Districts" VALUES (742, 58, 'DOĞANŞAR');
INSERT INTO public."Districts" VALUES (743, 58, 'GEMEREK');
INSERT INTO public."Districts" VALUES (744, 58, 'GÖLOVA');
INSERT INTO public."Districts" VALUES (745, 58, 'GÜRÜN');
INSERT INTO public."Districts" VALUES (746, 58, 'HAFİK');
INSERT INTO public."Districts" VALUES (747, 58, 'İMRANLI');
INSERT INTO public."Districts" VALUES (748, 58, 'KANGAL');
INSERT INTO public."Districts" VALUES (749, 58, 'KOYULHİSAR');
INSERT INTO public."Districts" VALUES (750, 58, 'ŞARKIŞLA');
INSERT INTO public."Districts" VALUES (751, 58, 'SUŞEHRİ');
INSERT INTO public."Districts" VALUES (752, 58, 'ULAŞ');
INSERT INTO public."Districts" VALUES (753, 58, 'YILDIZELİ');
INSERT INTO public."Districts" VALUES (754, 58, 'ZARA');
INSERT INTO public."Districts" VALUES (755, 59, 'ÇERKEZKÖY');
INSERT INTO public."Districts" VALUES (756, 59, 'ÇORLU');
INSERT INTO public."Districts" VALUES (757, 59, 'ERGENE');
INSERT INTO public."Districts" VALUES (758, 59, 'HAYRABOLU');
INSERT INTO public."Districts" VALUES (759, 59, 'KAPAKLI');
INSERT INTO public."Districts" VALUES (760, 59, 'MALKARA');
INSERT INTO public."Districts" VALUES (761, 59, 'MARMARAEREĞLİSİ');
INSERT INTO public."Districts" VALUES (762, 59, 'MURATLI');
INSERT INTO public."Districts" VALUES (763, 59, 'SARAY');
INSERT INTO public."Districts" VALUES (764, 59, 'ŞARKÖY');
INSERT INTO public."Districts" VALUES (765, 59, 'SÜLEYMANPAŞA');
INSERT INTO public."Districts" VALUES (766, 60, 'ALMUS');
INSERT INTO public."Districts" VALUES (767, 60, 'ARTOVA');
INSERT INTO public."Districts" VALUES (768, 60, 'BAŞÇİFTLİK');
INSERT INTO public."Districts" VALUES (769, 60, 'ERBAA');
INSERT INTO public."Districts" VALUES (770, 60, 'NİKSAR');
INSERT INTO public."Districts" VALUES (771, 60, 'PAZAR');
INSERT INTO public."Districts" VALUES (772, 60, 'REŞADİYE');
INSERT INTO public."Districts" VALUES (773, 60, 'SULUSARAY');
INSERT INTO public."Districts" VALUES (774, 60, 'TURHAL');
INSERT INTO public."Districts" VALUES (775, 60, 'YEŞİLYURT');
INSERT INTO public."Districts" VALUES (776, 60, 'ZİLE');
INSERT INTO public."Districts" VALUES (777, 61, 'AKÇAABAT');
INSERT INTO public."Districts" VALUES (778, 61, 'ARAKLI');
INSERT INTO public."Districts" VALUES (779, 61, 'ARSİN');
INSERT INTO public."Districts" VALUES (780, 61, 'BEŞİKDÜZÜ');
INSERT INTO public."Districts" VALUES (781, 61, 'ÇARŞIBAŞI');
INSERT INTO public."Districts" VALUES (782, 61, 'ÇAYKARA');
INSERT INTO public."Districts" VALUES (783, 61, 'DERNEKPAZARI');
INSERT INTO public."Districts" VALUES (784, 61, 'DÜZKÖY');
INSERT INTO public."Districts" VALUES (785, 61, 'HAYRAT');
INSERT INTO public."Districts" VALUES (786, 61, 'KÖPRÜBAŞI');
INSERT INTO public."Districts" VALUES (787, 61, 'MAÇKA');
INSERT INTO public."Districts" VALUES (788, 61, 'OF');
INSERT INTO public."Districts" VALUES (789, 61, 'ORTAHİSAR');
INSERT INTO public."Districts" VALUES (790, 61, 'ŞALPAZARI');
INSERT INTO public."Districts" VALUES (791, 61, 'SÜRMENE');
INSERT INTO public."Districts" VALUES (792, 61, 'TONYA');
INSERT INTO public."Districts" VALUES (793, 61, 'VAKFIKEBİR');
INSERT INTO public."Districts" VALUES (794, 61, 'YOMRA');
INSERT INTO public."Districts" VALUES (795, 62, 'ÇEMİŞGEZEK');
INSERT INTO public."Districts" VALUES (796, 62, 'HOZAT');
INSERT INTO public."Districts" VALUES (797, 62, 'MAZGİRT');
INSERT INTO public."Districts" VALUES (798, 62, 'NAZIMİYE');
INSERT INTO public."Districts" VALUES (799, 62, 'OVACIK');
INSERT INTO public."Districts" VALUES (800, 62, 'PERTEK');
INSERT INTO public."Districts" VALUES (801, 62, 'PÜLÜMÜR');
INSERT INTO public."Districts" VALUES (802, 63, 'AKÇAKALE');
INSERT INTO public."Districts" VALUES (803, 63, 'BİRECİK');
INSERT INTO public."Districts" VALUES (804, 63, 'BOZOVA');
INSERT INTO public."Districts" VALUES (805, 63, 'CEYLANPINAR');
INSERT INTO public."Districts" VALUES (806, 63, 'EYYÜBİYE');
INSERT INTO public."Districts" VALUES (807, 63, 'HALFETİ');
INSERT INTO public."Districts" VALUES (808, 63, 'HALİLİYE');
INSERT INTO public."Districts" VALUES (809, 63, 'HARRAN');
INSERT INTO public."Districts" VALUES (810, 63, 'HİLVAN');
INSERT INTO public."Districts" VALUES (811, 63, 'KARAKÖPRÜ');
INSERT INTO public."Districts" VALUES (812, 63, 'SİVEREK');
INSERT INTO public."Districts" VALUES (813, 63, 'SURUÇ');
INSERT INTO public."Districts" VALUES (814, 63, 'VİRANŞEHİR');
INSERT INTO public."Districts" VALUES (815, 64, 'BANAZ');
INSERT INTO public."Districts" VALUES (816, 64, 'EŞME');
INSERT INTO public."Districts" VALUES (817, 64, 'KARAHALLI');
INSERT INTO public."Districts" VALUES (818, 64, 'SİVASLI');
INSERT INTO public."Districts" VALUES (819, 64, 'ULUBEY');
INSERT INTO public."Districts" VALUES (820, 65, 'BAHÇESARAY');
INSERT INTO public."Districts" VALUES (821, 65, 'BAŞKALE');
INSERT INTO public."Districts" VALUES (822, 65, 'ÇALDIRAN');
INSERT INTO public."Districts" VALUES (823, 65, 'ÇATAK');
INSERT INTO public."Districts" VALUES (824, 65, 'EDREMİT');
INSERT INTO public."Districts" VALUES (825, 65, 'ERCİŞ');
INSERT INTO public."Districts" VALUES (826, 65, 'GEVAŞ');
INSERT INTO public."Districts" VALUES (827, 65, 'GÜRPINAR');
INSERT INTO public."Districts" VALUES (828, 65, 'İPEKYOLU');
INSERT INTO public."Districts" VALUES (829, 65, 'MURADİYE');
INSERT INTO public."Districts" VALUES (830, 65, 'ÖZALP');
INSERT INTO public."Districts" VALUES (831, 65, 'SARAY');
INSERT INTO public."Districts" VALUES (832, 65, 'TUŞBA');
INSERT INTO public."Districts" VALUES (833, 66, 'AKDAĞMADENİ');
INSERT INTO public."Districts" VALUES (834, 66, 'AYDINCIK');
INSERT INTO public."Districts" VALUES (835, 66, 'BOĞAZLIYAN');
INSERT INTO public."Districts" VALUES (836, 66, 'ÇANDIR');
INSERT INTO public."Districts" VALUES (837, 66, 'ÇAYIRALAN');
INSERT INTO public."Districts" VALUES (838, 66, 'ÇEKEREK');
INSERT INTO public."Districts" VALUES (839, 66, 'KADIŞEHRİ');
INSERT INTO public."Districts" VALUES (840, 66, 'SARAYKENT');
INSERT INTO public."Districts" VALUES (841, 66, 'SARIKAYA');
INSERT INTO public."Districts" VALUES (842, 66, 'ŞEFAATLİ');
INSERT INTO public."Districts" VALUES (843, 66, 'SORGUN');
INSERT INTO public."Districts" VALUES (844, 66, 'YENİFAKILI');
INSERT INTO public."Districts" VALUES (845, 66, 'YERKÖY');
INSERT INTO public."Districts" VALUES (846, 67, 'ALAPLI');
INSERT INTO public."Districts" VALUES (847, 67, 'ÇAYCUMA');
INSERT INTO public."Districts" VALUES (848, 67, 'DEVREK');
INSERT INTO public."Districts" VALUES (849, 67, 'EREĞLİ');
INSERT INTO public."Districts" VALUES (850, 67, 'GÖKÇEBEY');
INSERT INTO public."Districts" VALUES (851, 67, 'KİLİMLİ');
INSERT INTO public."Districts" VALUES (852, 67, 'KOZLU');
INSERT INTO public."Districts" VALUES (853, 68, 'AĞAÇÖREN');
INSERT INTO public."Districts" VALUES (854, 68, 'ESKİL');
INSERT INTO public."Districts" VALUES (855, 68, 'GÜLAĞAÇ');
INSERT INTO public."Districts" VALUES (856, 68, 'GÜZELYURT');
INSERT INTO public."Districts" VALUES (857, 68, 'ORTAKÖY');
INSERT INTO public."Districts" VALUES (858, 68, 'SARIYAHŞİ');
INSERT INTO public."Districts" VALUES (859, 68, 'SULTANHANI');
INSERT INTO public."Districts" VALUES (860, 69, 'AYDINTEPE');
INSERT INTO public."Districts" VALUES (861, 69, 'DEMİRÖZÜ');
INSERT INTO public."Districts" VALUES (862, 70, 'AYRANCI');
INSERT INTO public."Districts" VALUES (863, 70, 'BAŞYAYLA');
INSERT INTO public."Districts" VALUES (864, 70, 'ERMENEK');
INSERT INTO public."Districts" VALUES (865, 70, 'KAZIMKARABEKİR');
INSERT INTO public."Districts" VALUES (866, 70, 'SARIVELİLER');
INSERT INTO public."Districts" VALUES (867, 71, 'BAHŞILI');
INSERT INTO public."Districts" VALUES (868, 71, 'BALIŞEYH');
INSERT INTO public."Districts" VALUES (869, 71, 'ÇELEBİ');
INSERT INTO public."Districts" VALUES (870, 71, 'DELİCE');
INSERT INTO public."Districts" VALUES (871, 71, 'KARAKEÇİLİ');
INSERT INTO public."Districts" VALUES (872, 71, 'KESKİN');
INSERT INTO public."Districts" VALUES (873, 71, 'SULAKYURT');
INSERT INTO public."Districts" VALUES (874, 71, 'YAHŞİHAN');
INSERT INTO public."Districts" VALUES (875, 72, 'BEŞİRİ');
INSERT INTO public."Districts" VALUES (876, 72, 'GERCÜŞ');
INSERT INTO public."Districts" VALUES (877, 72, 'HASANKEYF');
INSERT INTO public."Districts" VALUES (878, 72, 'KOZLUK');
INSERT INTO public."Districts" VALUES (879, 72, 'SASON');
INSERT INTO public."Districts" VALUES (880, 73, 'BEYTÜŞŞEBAP');
INSERT INTO public."Districts" VALUES (881, 73, 'CİZRE');
INSERT INTO public."Districts" VALUES (882, 73, 'GÜÇLÜKONAK');
INSERT INTO public."Districts" VALUES (883, 73, 'İDİL');
INSERT INTO public."Districts" VALUES (884, 73, 'SİLOPİ');
INSERT INTO public."Districts" VALUES (885, 73, 'ULUDERE');
INSERT INTO public."Districts" VALUES (886, 74, 'AMASRA');
INSERT INTO public."Districts" VALUES (887, 74, 'KURUCAŞİLE');
INSERT INTO public."Districts" VALUES (888, 74, 'ULUS');
INSERT INTO public."Districts" VALUES (889, 75, 'ÇILDIR');
INSERT INTO public."Districts" VALUES (890, 75, 'DAMAL');
INSERT INTO public."Districts" VALUES (891, 75, 'GÖLE');
INSERT INTO public."Districts" VALUES (892, 75, 'HANAK');
INSERT INTO public."Districts" VALUES (893, 75, 'POSOF');
INSERT INTO public."Districts" VALUES (894, 76, 'ARALIK');
INSERT INTO public."Districts" VALUES (895, 76, 'KARAKOYUNLU');
INSERT INTO public."Districts" VALUES (896, 76, 'TUZLUCA');
INSERT INTO public."Districts" VALUES (897, 77, 'ALTINOVA');
INSERT INTO public."Districts" VALUES (898, 77, 'ARMUTLU');
INSERT INTO public."Districts" VALUES (899, 77, 'ÇİFTLİKKÖY');
INSERT INTO public."Districts" VALUES (900, 77, 'ÇINARCIK');
INSERT INTO public."Districts" VALUES (901, 77, 'TERMAL');
INSERT INTO public."Districts" VALUES (902, 78, 'EFLANİ');
INSERT INTO public."Districts" VALUES (903, 78, 'ESKİPAZAR');
INSERT INTO public."Districts" VALUES (904, 78, 'OVACIK');
INSERT INTO public."Districts" VALUES (905, 78, 'SAFRANBOLU');
INSERT INTO public."Districts" VALUES (906, 78, 'YENİCE');
INSERT INTO public."Districts" VALUES (907, 79, 'ELBEYLİ');
INSERT INTO public."Districts" VALUES (908, 79, 'MUSABEYLİ');
INSERT INTO public."Districts" VALUES (909, 79, 'POLATELİ');
INSERT INTO public."Districts" VALUES (910, 80, 'BAHÇE');
INSERT INTO public."Districts" VALUES (911, 80, 'DÜZİÇİ');
INSERT INTO public."Districts" VALUES (912, 80, 'HASANBEYLİ');
INSERT INTO public."Districts" VALUES (913, 80, 'KADİRLİ');
INSERT INTO public."Districts" VALUES (914, 80, 'SUMBAS');
INSERT INTO public."Districts" VALUES (915, 80, 'TOPRAKKALE');
INSERT INTO public."Districts" VALUES (916, 81, 'AKÇAKOCA');
INSERT INTO public."Districts" VALUES (917, 81, 'ÇİLİMLİ');
INSERT INTO public."Districts" VALUES (918, 81, 'CUMAYERİ');
INSERT INTO public."Districts" VALUES (919, 81, 'GÖLYAKA');
INSERT INTO public."Districts" VALUES (920, 81, 'GÜMÜŞOVA');
INSERT INTO public."Districts" VALUES (921, 81, 'KAYNAŞLI');
INSERT INTO public."Districts" VALUES (922, 81, 'YIĞILCA');


--
-- TOC entry 3339 (class 0 OID 0)
-- Dependencies: 214
-- Name: Cities_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Cities_Id_seq"', 81, true);


--
-- TOC entry 3340 (class 0 OID 0)
-- Dependencies: 216
-- Name: Districts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Districts_Id_seq"', 922, true);


--
-- TOC entry 3182 (class 2606 OID 16433)
-- Name: Cities PK_Cities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cities"
    ADD CONSTRAINT "PK_Cities" PRIMARY KEY ("Id");


--
-- TOC entry 3185 (class 2606 OID 16439)
-- Name: Districts PK_Districts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Districts"
    ADD CONSTRAINT "PK_Districts" PRIMARY KEY ("Id");


--
-- TOC entry 3183 (class 1259 OID 16445)
-- Name: IX_Districts_CityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Districts_CityId" ON public."Districts" USING btree ("CityId");


--
-- TOC entry 3186 (class 2606 OID 16440)
-- Name: Districts FK_Districts_Cities_CityId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Districts"
    ADD CONSTRAINT "FK_Districts_Cities_CityId" FOREIGN KEY ("CityId") REFERENCES public."Cities"("Id") ON DELETE CASCADE;


-- Completed on 2023-02-09 17:37:39

--
-- PostgreSQL database dump complete
--

